<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class CorpusGroup extends Validate{

protected $rule =   [
        'id' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'name' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'create_time' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'update_time' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'user_name' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'id.require' => 'id不能为空',
'id.number' => 'id不是数字',
'id.float' => 'id不是小数',
'id.boolean' => 'id不是布尔值',
'id.email' => 'id不是邮箱地址',
'id.array' => 'id不是数组',
'id.accepted' => 'id请确认',
'id.date' => 'id不是有效日期',
'id.alpha' => 'id不是字母',
'id.alphaNum' => 'id不是字母和数字',
'id.alphaDash' => 'id不是字母和数字和下划线及破折号',
'id.chs' => 'id只能是汉字',
'id.chsAlpha' => 'id只能是汉字、字母',
'id.chsAlphaNum' => 'id只能是汉字、字母和数字',
'id.chsDash' => 'id只能是汉字、字母、数字和下划线_及破折号-',
'id.activeUrl' => 'id不是有效的域名或者IP',
'id.url' => 'id不是有效的URL地址',
'id.ip' => 'id不是有效的IP地址',
'id.length' => 'id长度不符',
'id.max' => 'id超出最大长度',
'id.min' => 'id低于最小长度',
'name.require' => '组名不能为空',
'name.number' => '组名不是数字',
'name.float' => '组名不是小数',
'name.boolean' => '组名不是布尔值',
'name.email' => '组名不是邮箱地址',
'name.array' => '组名不是数组',
'name.accepted' => '组名请确认',
'name.date' => '组名不是有效日期',
'name.alpha' => '组名不是字母',
'name.alphaNum' => '组名不是字母和数字',
'name.alphaDash' => '组名不是字母和数字和下划线及破折号',
'name.chs' => '组名只能是汉字',
'name.chsAlpha' => '组名只能是汉字、字母',
'name.chsAlphaNum' => '组名只能是汉字、字母和数字',
'name.chsDash' => '组名只能是汉字、字母、数字和下划线_及破折号-',
'name.activeUrl' => '组名不是有效的域名或者IP',
'name.url' => '组名不是有效的URL地址',
'name.ip' => '组名不是有效的IP地址',
'name.length' => '组名长度不符',
'name.max' => '组名超出最大长度',
'name.min' => '组名低于最小长度',
'create_time.require' => 'create_time不能为空',
'create_time.number' => 'create_time不是数字',
'create_time.float' => 'create_time不是小数',
'create_time.boolean' => 'create_time不是布尔值',
'create_time.email' => 'create_time不是邮箱地址',
'create_time.array' => 'create_time不是数组',
'create_time.accepted' => 'create_time请确认',
'create_time.date' => 'create_time不是有效日期',
'create_time.alpha' => 'create_time不是字母',
'create_time.alphaNum' => 'create_time不是字母和数字',
'create_time.alphaDash' => 'create_time不是字母和数字和下划线及破折号',
'create_time.chs' => 'create_time只能是汉字',
'create_time.chsAlpha' => 'create_time只能是汉字、字母',
'create_time.chsAlphaNum' => 'create_time只能是汉字、字母和数字',
'create_time.chsDash' => 'create_time只能是汉字、字母、数字和下划线_及破折号-',
'create_time.activeUrl' => 'create_time不是有效的域名或者IP',
'create_time.url' => 'create_time不是有效的URL地址',
'create_time.ip' => 'create_time不是有效的IP地址',
'create_time.length' => 'create_time长度不符',
'create_time.max' => 'create_time超出最大长度',
'create_time.min' => 'create_time低于最小长度',
'update_time.require' => 'update_time不能为空',
'update_time.number' => 'update_time不是数字',
'update_time.float' => 'update_time不是小数',
'update_time.boolean' => 'update_time不是布尔值',
'update_time.email' => 'update_time不是邮箱地址',
'update_time.array' => 'update_time不是数组',
'update_time.accepted' => 'update_time请确认',
'update_time.date' => 'update_time不是有效日期',
'update_time.alpha' => 'update_time不是字母',
'update_time.alphaNum' => 'update_time不是字母和数字',
'update_time.alphaDash' => 'update_time不是字母和数字和下划线及破折号',
'update_time.chs' => 'update_time只能是汉字',
'update_time.chsAlpha' => 'update_time只能是汉字、字母',
'update_time.chsAlphaNum' => 'update_time只能是汉字、字母和数字',
'update_time.chsDash' => 'update_time只能是汉字、字母、数字和下划线_及破折号-',
'update_time.activeUrl' => 'update_time不是有效的域名或者IP',
'update_time.url' => 'update_time不是有效的URL地址',
'update_time.ip' => 'update_time不是有效的IP地址',
'update_time.length' => 'update_time长度不符',
'update_time.max' => 'update_time超出最大长度',
'update_time.min' => 'update_time低于最小长度',
'user_name.require' => 'user_name不能为空',
'user_name.number' => 'user_name不是数字',
'user_name.float' => 'user_name不是小数',
'user_name.boolean' => 'user_name不是布尔值',
'user_name.email' => 'user_name不是邮箱地址',
'user_name.array' => 'user_name不是数组',
'user_name.accepted' => 'user_name请确认',
'user_name.date' => 'user_name不是有效日期',
'user_name.alpha' => 'user_name不是字母',
'user_name.alphaNum' => 'user_name不是字母和数字',
'user_name.alphaDash' => 'user_name不是字母和数字和下划线及破折号',
'user_name.chs' => 'user_name只能是汉字',
'user_name.chsAlpha' => 'user_name只能是汉字、字母',
'user_name.chsAlphaNum' => 'user_name只能是汉字、字母和数字',
'user_name.chsDash' => 'user_name只能是汉字、字母、数字和下划线_及破折号-',
'user_name.activeUrl' => 'user_name不是有效的域名或者IP',
'user_name.url' => 'user_name不是有效的URL地址',
'user_name.ip' => 'user_name不是有效的IP地址',
'user_name.length' => 'user_name长度不符',
'user_name.max' => 'user_name超出最大长度',
'user_name.min' => 'user_name低于最小长度',
];

protected $scene =   [
    'add'=>['id','name','create_time','update_time','user_name',],
    'edit'=>['id','name','create_time','update_time','user_name',],
    'ck_id'=>['id']
];

}
