<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsmemberpub extends Validate{

protected $rule =   [
        'userid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'todayinfodate' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'todayaddinfo' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'todaydate' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'todaydown' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'authstr' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'userid.require' => 'userid不能为空',
'userid.number' => 'userid不是数字',
'userid.float' => 'userid不是小数',
'userid.boolean' => 'userid不是布尔值',
'userid.email' => 'userid不是邮箱地址',
'userid.array' => 'userid不是数组',
'userid.accepted' => 'userid请确认',
'userid.date' => 'userid不是有效日期',
'userid.alpha' => 'userid不是字母',
'userid.alphaNum' => 'userid不是字母和数字',
'userid.alphaDash' => 'userid不是字母和数字和下划线及破折号',
'userid.chs' => 'userid只能是汉字',
'userid.chsAlpha' => 'userid只能是汉字、字母',
'userid.chsAlphaNum' => 'userid只能是汉字、字母和数字',
'userid.chsDash' => 'userid只能是汉字、字母、数字和下划线_及破折号-',
'userid.activeUrl' => 'userid不是有效的域名或者IP',
'userid.url' => 'userid不是有效的URL地址',
'userid.ip' => 'userid不是有效的IP地址',
'userid.length' => 'userid长度不符',
'userid.max' => 'userid超出最大长度',
'userid.min' => 'userid低于最小长度',
'todayinfodate.require' => 'todayinfodate不能为空',
'todayinfodate.number' => 'todayinfodate不是数字',
'todayinfodate.float' => 'todayinfodate不是小数',
'todayinfodate.boolean' => 'todayinfodate不是布尔值',
'todayinfodate.email' => 'todayinfodate不是邮箱地址',
'todayinfodate.array' => 'todayinfodate不是数组',
'todayinfodate.accepted' => 'todayinfodate请确认',
'todayinfodate.date' => 'todayinfodate不是有效日期',
'todayinfodate.alpha' => 'todayinfodate不是字母',
'todayinfodate.alphaNum' => 'todayinfodate不是字母和数字',
'todayinfodate.alphaDash' => 'todayinfodate不是字母和数字和下划线及破折号',
'todayinfodate.chs' => 'todayinfodate只能是汉字',
'todayinfodate.chsAlpha' => 'todayinfodate只能是汉字、字母',
'todayinfodate.chsAlphaNum' => 'todayinfodate只能是汉字、字母和数字',
'todayinfodate.chsDash' => 'todayinfodate只能是汉字、字母、数字和下划线_及破折号-',
'todayinfodate.activeUrl' => 'todayinfodate不是有效的域名或者IP',
'todayinfodate.url' => 'todayinfodate不是有效的URL地址',
'todayinfodate.ip' => 'todayinfodate不是有效的IP地址',
'todayinfodate.length' => 'todayinfodate长度不符',
'todayinfodate.max' => 'todayinfodate超出最大长度',
'todayinfodate.min' => 'todayinfodate低于最小长度',
'todayaddinfo.require' => 'todayaddinfo不能为空',
'todayaddinfo.number' => 'todayaddinfo不是数字',
'todayaddinfo.float' => 'todayaddinfo不是小数',
'todayaddinfo.boolean' => 'todayaddinfo不是布尔值',
'todayaddinfo.email' => 'todayaddinfo不是邮箱地址',
'todayaddinfo.array' => 'todayaddinfo不是数组',
'todayaddinfo.accepted' => 'todayaddinfo请确认',
'todayaddinfo.date' => 'todayaddinfo不是有效日期',
'todayaddinfo.alpha' => 'todayaddinfo不是字母',
'todayaddinfo.alphaNum' => 'todayaddinfo不是字母和数字',
'todayaddinfo.alphaDash' => 'todayaddinfo不是字母和数字和下划线及破折号',
'todayaddinfo.chs' => 'todayaddinfo只能是汉字',
'todayaddinfo.chsAlpha' => 'todayaddinfo只能是汉字、字母',
'todayaddinfo.chsAlphaNum' => 'todayaddinfo只能是汉字、字母和数字',
'todayaddinfo.chsDash' => 'todayaddinfo只能是汉字、字母、数字和下划线_及破折号-',
'todayaddinfo.activeUrl' => 'todayaddinfo不是有效的域名或者IP',
'todayaddinfo.url' => 'todayaddinfo不是有效的URL地址',
'todayaddinfo.ip' => 'todayaddinfo不是有效的IP地址',
'todayaddinfo.length' => 'todayaddinfo长度不符',
'todayaddinfo.max' => 'todayaddinfo超出最大长度',
'todayaddinfo.min' => 'todayaddinfo低于最小长度',
'todaydate.require' => 'todaydate不能为空',
'todaydate.number' => 'todaydate不是数字',
'todaydate.float' => 'todaydate不是小数',
'todaydate.boolean' => 'todaydate不是布尔值',
'todaydate.email' => 'todaydate不是邮箱地址',
'todaydate.array' => 'todaydate不是数组',
'todaydate.accepted' => 'todaydate请确认',
'todaydate.date' => 'todaydate不是有效日期',
'todaydate.alpha' => 'todaydate不是字母',
'todaydate.alphaNum' => 'todaydate不是字母和数字',
'todaydate.alphaDash' => 'todaydate不是字母和数字和下划线及破折号',
'todaydate.chs' => 'todaydate只能是汉字',
'todaydate.chsAlpha' => 'todaydate只能是汉字、字母',
'todaydate.chsAlphaNum' => 'todaydate只能是汉字、字母和数字',
'todaydate.chsDash' => 'todaydate只能是汉字、字母、数字和下划线_及破折号-',
'todaydate.activeUrl' => 'todaydate不是有效的域名或者IP',
'todaydate.url' => 'todaydate不是有效的URL地址',
'todaydate.ip' => 'todaydate不是有效的IP地址',
'todaydate.length' => 'todaydate长度不符',
'todaydate.max' => 'todaydate超出最大长度',
'todaydate.min' => 'todaydate低于最小长度',
'todaydown.require' => 'todaydown不能为空',
'todaydown.number' => 'todaydown不是数字',
'todaydown.float' => 'todaydown不是小数',
'todaydown.boolean' => 'todaydown不是布尔值',
'todaydown.email' => 'todaydown不是邮箱地址',
'todaydown.array' => 'todaydown不是数组',
'todaydown.accepted' => 'todaydown请确认',
'todaydown.date' => 'todaydown不是有效日期',
'todaydown.alpha' => 'todaydown不是字母',
'todaydown.alphaNum' => 'todaydown不是字母和数字',
'todaydown.alphaDash' => 'todaydown不是字母和数字和下划线及破折号',
'todaydown.chs' => 'todaydown只能是汉字',
'todaydown.chsAlpha' => 'todaydown只能是汉字、字母',
'todaydown.chsAlphaNum' => 'todaydown只能是汉字、字母和数字',
'todaydown.chsDash' => 'todaydown只能是汉字、字母、数字和下划线_及破折号-',
'todaydown.activeUrl' => 'todaydown不是有效的域名或者IP',
'todaydown.url' => 'todaydown不是有效的URL地址',
'todaydown.ip' => 'todaydown不是有效的IP地址',
'todaydown.length' => 'todaydown长度不符',
'todaydown.max' => 'todaydown超出最大长度',
'todaydown.min' => 'todaydown低于最小长度',
'authstr.require' => 'authstr不能为空',
'authstr.number' => 'authstr不是数字',
'authstr.float' => 'authstr不是小数',
'authstr.boolean' => 'authstr不是布尔值',
'authstr.email' => 'authstr不是邮箱地址',
'authstr.array' => 'authstr不是数组',
'authstr.accepted' => 'authstr请确认',
'authstr.date' => 'authstr不是有效日期',
'authstr.alpha' => 'authstr不是字母',
'authstr.alphaNum' => 'authstr不是字母和数字',
'authstr.alphaDash' => 'authstr不是字母和数字和下划线及破折号',
'authstr.chs' => 'authstr只能是汉字',
'authstr.chsAlpha' => 'authstr只能是汉字、字母',
'authstr.chsAlphaNum' => 'authstr只能是汉字、字母和数字',
'authstr.chsDash' => 'authstr只能是汉字、字母、数字和下划线_及破折号-',
'authstr.activeUrl' => 'authstr不是有效的域名或者IP',
'authstr.url' => 'authstr不是有效的URL地址',
'authstr.ip' => 'authstr不是有效的IP地址',
'authstr.length' => 'authstr长度不符',
'authstr.max' => 'authstr超出最大长度',
'authstr.min' => 'authstr低于最小长度',
];

protected $scene =   [
    'add'=>['userid','todayinfodate','todayaddinfo','todaydate','todaydown','authstr',],
    'edit'=>['userid','todayinfodate','todayaddinfo','todaydate','todaydown','authstr',],
    'ck_id'=>['id']
];

}
