<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewslinktmp extends Validate{

protected $rule =   [
        'newsurl' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'checkrnd' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'linkid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'titlepic' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'newsurl.require' => 'newsurl不能为空',
'newsurl.number' => 'newsurl不是数字',
'newsurl.float' => 'newsurl不是小数',
'newsurl.boolean' => 'newsurl不是布尔值',
'newsurl.email' => 'newsurl不是邮箱地址',
'newsurl.array' => 'newsurl不是数组',
'newsurl.accepted' => 'newsurl请确认',
'newsurl.date' => 'newsurl不是有效日期',
'newsurl.alpha' => 'newsurl不是字母',
'newsurl.alphaNum' => 'newsurl不是字母和数字',
'newsurl.alphaDash' => 'newsurl不是字母和数字和下划线及破折号',
'newsurl.chs' => 'newsurl只能是汉字',
'newsurl.chsAlpha' => 'newsurl只能是汉字、字母',
'newsurl.chsAlphaNum' => 'newsurl只能是汉字、字母和数字',
'newsurl.chsDash' => 'newsurl只能是汉字、字母、数字和下划线_及破折号-',
'newsurl.activeUrl' => 'newsurl不是有效的域名或者IP',
'newsurl.url' => 'newsurl不是有效的URL地址',
'newsurl.ip' => 'newsurl不是有效的IP地址',
'newsurl.length' => 'newsurl长度不符',
'newsurl.max' => 'newsurl超出最大长度',
'newsurl.min' => 'newsurl低于最小长度',
'checkrnd.require' => 'checkrnd不能为空',
'checkrnd.number' => 'checkrnd不是数字',
'checkrnd.float' => 'checkrnd不是小数',
'checkrnd.boolean' => 'checkrnd不是布尔值',
'checkrnd.email' => 'checkrnd不是邮箱地址',
'checkrnd.array' => 'checkrnd不是数组',
'checkrnd.accepted' => 'checkrnd请确认',
'checkrnd.date' => 'checkrnd不是有效日期',
'checkrnd.alpha' => 'checkrnd不是字母',
'checkrnd.alphaNum' => 'checkrnd不是字母和数字',
'checkrnd.alphaDash' => 'checkrnd不是字母和数字和下划线及破折号',
'checkrnd.chs' => 'checkrnd只能是汉字',
'checkrnd.chsAlpha' => 'checkrnd只能是汉字、字母',
'checkrnd.chsAlphaNum' => 'checkrnd只能是汉字、字母和数字',
'checkrnd.chsDash' => 'checkrnd只能是汉字、字母、数字和下划线_及破折号-',
'checkrnd.activeUrl' => 'checkrnd不是有效的域名或者IP',
'checkrnd.url' => 'checkrnd不是有效的URL地址',
'checkrnd.ip' => 'checkrnd不是有效的IP地址',
'checkrnd.length' => 'checkrnd长度不符',
'checkrnd.max' => 'checkrnd超出最大长度',
'checkrnd.min' => 'checkrnd低于最小长度',
'linkid.require' => 'linkid不能为空',
'linkid.number' => 'linkid不是数字',
'linkid.float' => 'linkid不是小数',
'linkid.boolean' => 'linkid不是布尔值',
'linkid.email' => 'linkid不是邮箱地址',
'linkid.array' => 'linkid不是数组',
'linkid.accepted' => 'linkid请确认',
'linkid.date' => 'linkid不是有效日期',
'linkid.alpha' => 'linkid不是字母',
'linkid.alphaNum' => 'linkid不是字母和数字',
'linkid.alphaDash' => 'linkid不是字母和数字和下划线及破折号',
'linkid.chs' => 'linkid只能是汉字',
'linkid.chsAlpha' => 'linkid只能是汉字、字母',
'linkid.chsAlphaNum' => 'linkid只能是汉字、字母和数字',
'linkid.chsDash' => 'linkid只能是汉字、字母、数字和下划线_及破折号-',
'linkid.activeUrl' => 'linkid不是有效的域名或者IP',
'linkid.url' => 'linkid不是有效的URL地址',
'linkid.ip' => 'linkid不是有效的IP地址',
'linkid.length' => 'linkid长度不符',
'linkid.max' => 'linkid超出最大长度',
'linkid.min' => 'linkid低于最小长度',
'titlepic.require' => 'titlepic不能为空',
'titlepic.number' => 'titlepic不是数字',
'titlepic.float' => 'titlepic不是小数',
'titlepic.boolean' => 'titlepic不是布尔值',
'titlepic.email' => 'titlepic不是邮箱地址',
'titlepic.array' => 'titlepic不是数组',
'titlepic.accepted' => 'titlepic请确认',
'titlepic.date' => 'titlepic不是有效日期',
'titlepic.alpha' => 'titlepic不是字母',
'titlepic.alphaNum' => 'titlepic不是字母和数字',
'titlepic.alphaDash' => 'titlepic不是字母和数字和下划线及破折号',
'titlepic.chs' => 'titlepic只能是汉字',
'titlepic.chsAlpha' => 'titlepic只能是汉字、字母',
'titlepic.chsAlphaNum' => 'titlepic只能是汉字、字母和数字',
'titlepic.chsDash' => 'titlepic只能是汉字、字母、数字和下划线_及破折号-',
'titlepic.activeUrl' => 'titlepic不是有效的域名或者IP',
'titlepic.url' => 'titlepic不是有效的URL地址',
'titlepic.ip' => 'titlepic不是有效的IP地址',
'titlepic.length' => 'titlepic长度不符',
'titlepic.max' => 'titlepic超出最大长度',
'titlepic.min' => 'titlepic低于最小长度',
];

protected $scene =   [
    'add'=>['newsurl','checkrnd','linkid','titlepic',],
    'edit'=>['newsurl','checkrnd','linkid','titlepic',],
    'ck_id'=>['id']
];

}
