<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsplayer extends Validate{

protected $rule =   [
        'id' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'player' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'filename' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'bz' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'id.require' => 'id不能为空',
'id.number' => 'id不是数字',
'id.float' => 'id不是小数',
'id.boolean' => 'id不是布尔值',
'id.email' => 'id不是邮箱地址',
'id.array' => 'id不是数组',
'id.accepted' => 'id请确认',
'id.date' => 'id不是有效日期',
'id.alpha' => 'id不是字母',
'id.alphaNum' => 'id不是字母和数字',
'id.alphaDash' => 'id不是字母和数字和下划线及破折号',
'id.chs' => 'id只能是汉字',
'id.chsAlpha' => 'id只能是汉字、字母',
'id.chsAlphaNum' => 'id只能是汉字、字母和数字',
'id.chsDash' => 'id只能是汉字、字母、数字和下划线_及破折号-',
'id.activeUrl' => 'id不是有效的域名或者IP',
'id.url' => 'id不是有效的URL地址',
'id.ip' => 'id不是有效的IP地址',
'id.length' => 'id长度不符',
'id.max' => 'id超出最大长度',
'id.min' => 'id低于最小长度',
'player.require' => 'player不能为空',
'player.number' => 'player不是数字',
'player.float' => 'player不是小数',
'player.boolean' => 'player不是布尔值',
'player.email' => 'player不是邮箱地址',
'player.array' => 'player不是数组',
'player.accepted' => 'player请确认',
'player.date' => 'player不是有效日期',
'player.alpha' => 'player不是字母',
'player.alphaNum' => 'player不是字母和数字',
'player.alphaDash' => 'player不是字母和数字和下划线及破折号',
'player.chs' => 'player只能是汉字',
'player.chsAlpha' => 'player只能是汉字、字母',
'player.chsAlphaNum' => 'player只能是汉字、字母和数字',
'player.chsDash' => 'player只能是汉字、字母、数字和下划线_及破折号-',
'player.activeUrl' => 'player不是有效的域名或者IP',
'player.url' => 'player不是有效的URL地址',
'player.ip' => 'player不是有效的IP地址',
'player.length' => 'player长度不符',
'player.max' => 'player超出最大长度',
'player.min' => 'player低于最小长度',
'filename.require' => 'filename不能为空',
'filename.number' => 'filename不是数字',
'filename.float' => 'filename不是小数',
'filename.boolean' => 'filename不是布尔值',
'filename.email' => 'filename不是邮箱地址',
'filename.array' => 'filename不是数组',
'filename.accepted' => 'filename请确认',
'filename.date' => 'filename不是有效日期',
'filename.alpha' => 'filename不是字母',
'filename.alphaNum' => 'filename不是字母和数字',
'filename.alphaDash' => 'filename不是字母和数字和下划线及破折号',
'filename.chs' => 'filename只能是汉字',
'filename.chsAlpha' => 'filename只能是汉字、字母',
'filename.chsAlphaNum' => 'filename只能是汉字、字母和数字',
'filename.chsDash' => 'filename只能是汉字、字母、数字和下划线_及破折号-',
'filename.activeUrl' => 'filename不是有效的域名或者IP',
'filename.url' => 'filename不是有效的URL地址',
'filename.ip' => 'filename不是有效的IP地址',
'filename.length' => 'filename长度不符',
'filename.max' => 'filename超出最大长度',
'filename.min' => 'filename低于最小长度',
'bz.require' => 'bz不能为空',
'bz.number' => 'bz不是数字',
'bz.float' => 'bz不是小数',
'bz.boolean' => 'bz不是布尔值',
'bz.email' => 'bz不是邮箱地址',
'bz.array' => 'bz不是数组',
'bz.accepted' => 'bz请确认',
'bz.date' => 'bz不是有效日期',
'bz.alpha' => 'bz不是字母',
'bz.alphaNum' => 'bz不是字母和数字',
'bz.alphaDash' => 'bz不是字母和数字和下划线及破折号',
'bz.chs' => 'bz只能是汉字',
'bz.chsAlpha' => 'bz只能是汉字、字母',
'bz.chsAlphaNum' => 'bz只能是汉字、字母和数字',
'bz.chsDash' => 'bz只能是汉字、字母、数字和下划线_及破折号-',
'bz.activeUrl' => 'bz不是有效的域名或者IP',
'bz.url' => 'bz不是有效的URL地址',
'bz.ip' => 'bz不是有效的IP地址',
'bz.length' => 'bz长度不符',
'bz.max' => 'bz超出最大长度',
'bz.min' => 'bz低于最小长度',
];

protected $scene =   [
    'add'=>['id','player','filename','bz',],
    'edit'=>['id','player','filename','bz',],
    'ck_id'=>['id']
];

}
