<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsgbookclass extends Validate{

protected $rule =   [
        'bid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'bname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'checked' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'groupid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'bid.require' => 'bid不能为空',
'bid.number' => 'bid不是数字',
'bid.float' => 'bid不是小数',
'bid.boolean' => 'bid不是布尔值',
'bid.email' => 'bid不是邮箱地址',
'bid.array' => 'bid不是数组',
'bid.accepted' => 'bid请确认',
'bid.date' => 'bid不是有效日期',
'bid.alpha' => 'bid不是字母',
'bid.alphaNum' => 'bid不是字母和数字',
'bid.alphaDash' => 'bid不是字母和数字和下划线及破折号',
'bid.chs' => 'bid只能是汉字',
'bid.chsAlpha' => 'bid只能是汉字、字母',
'bid.chsAlphaNum' => 'bid只能是汉字、字母和数字',
'bid.chsDash' => 'bid只能是汉字、字母、数字和下划线_及破折号-',
'bid.activeUrl' => 'bid不是有效的域名或者IP',
'bid.url' => 'bid不是有效的URL地址',
'bid.ip' => 'bid不是有效的IP地址',
'bid.length' => 'bid长度不符',
'bid.max' => 'bid超出最大长度',
'bid.min' => 'bid低于最小长度',
'bname.require' => 'bname不能为空',
'bname.number' => 'bname不是数字',
'bname.float' => 'bname不是小数',
'bname.boolean' => 'bname不是布尔值',
'bname.email' => 'bname不是邮箱地址',
'bname.array' => 'bname不是数组',
'bname.accepted' => 'bname请确认',
'bname.date' => 'bname不是有效日期',
'bname.alpha' => 'bname不是字母',
'bname.alphaNum' => 'bname不是字母和数字',
'bname.alphaDash' => 'bname不是字母和数字和下划线及破折号',
'bname.chs' => 'bname只能是汉字',
'bname.chsAlpha' => 'bname只能是汉字、字母',
'bname.chsAlphaNum' => 'bname只能是汉字、字母和数字',
'bname.chsDash' => 'bname只能是汉字、字母、数字和下划线_及破折号-',
'bname.activeUrl' => 'bname不是有效的域名或者IP',
'bname.url' => 'bname不是有效的URL地址',
'bname.ip' => 'bname不是有效的IP地址',
'bname.length' => 'bname长度不符',
'bname.max' => 'bname超出最大长度',
'bname.min' => 'bname低于最小长度',
'checked.require' => 'checked不能为空',
'checked.number' => 'checked不是数字',
'checked.float' => 'checked不是小数',
'checked.boolean' => 'checked不是布尔值',
'checked.email' => 'checked不是邮箱地址',
'checked.array' => 'checked不是数组',
'checked.accepted' => 'checked请确认',
'checked.date' => 'checked不是有效日期',
'checked.alpha' => 'checked不是字母',
'checked.alphaNum' => 'checked不是字母和数字',
'checked.alphaDash' => 'checked不是字母和数字和下划线及破折号',
'checked.chs' => 'checked只能是汉字',
'checked.chsAlpha' => 'checked只能是汉字、字母',
'checked.chsAlphaNum' => 'checked只能是汉字、字母和数字',
'checked.chsDash' => 'checked只能是汉字、字母、数字和下划线_及破折号-',
'checked.activeUrl' => 'checked不是有效的域名或者IP',
'checked.url' => 'checked不是有效的URL地址',
'checked.ip' => 'checked不是有效的IP地址',
'checked.length' => 'checked长度不符',
'checked.max' => 'checked超出最大长度',
'checked.min' => 'checked低于最小长度',
'groupid.require' => 'groupid不能为空',
'groupid.number' => 'groupid不是数字',
'groupid.float' => 'groupid不是小数',
'groupid.boolean' => 'groupid不是布尔值',
'groupid.email' => 'groupid不是邮箱地址',
'groupid.array' => 'groupid不是数组',
'groupid.accepted' => 'groupid请确认',
'groupid.date' => 'groupid不是有效日期',
'groupid.alpha' => 'groupid不是字母',
'groupid.alphaNum' => 'groupid不是字母和数字',
'groupid.alphaDash' => 'groupid不是字母和数字和下划线及破折号',
'groupid.chs' => 'groupid只能是汉字',
'groupid.chsAlpha' => 'groupid只能是汉字、字母',
'groupid.chsAlphaNum' => 'groupid只能是汉字、字母和数字',
'groupid.chsDash' => 'groupid只能是汉字、字母、数字和下划线_及破折号-',
'groupid.activeUrl' => 'groupid不是有效的域名或者IP',
'groupid.url' => 'groupid不是有效的URL地址',
'groupid.ip' => 'groupid不是有效的IP地址',
'groupid.length' => 'groupid长度不符',
'groupid.max' => 'groupid超出最大长度',
'groupid.min' => 'groupid低于最小长度',
];

protected $scene =   [
    'add'=>['bid','bname','checked','groupid',],
    'edit'=>['bid','bname','checked','groupid',],
    'ck_id'=>['id']
];

}
