<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsprinttemp extends Validate{

protected $rule =   [
        'tempid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'tempname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'temptext' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'isdefault' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'showdate' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'modid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'tempid.require' => 'tempid不能为空',
'tempid.number' => 'tempid不是数字',
'tempid.float' => 'tempid不是小数',
'tempid.boolean' => 'tempid不是布尔值',
'tempid.email' => 'tempid不是邮箱地址',
'tempid.array' => 'tempid不是数组',
'tempid.accepted' => 'tempid请确认',
'tempid.date' => 'tempid不是有效日期',
'tempid.alpha' => 'tempid不是字母',
'tempid.alphaNum' => 'tempid不是字母和数字',
'tempid.alphaDash' => 'tempid不是字母和数字和下划线及破折号',
'tempid.chs' => 'tempid只能是汉字',
'tempid.chsAlpha' => 'tempid只能是汉字、字母',
'tempid.chsAlphaNum' => 'tempid只能是汉字、字母和数字',
'tempid.chsDash' => 'tempid只能是汉字、字母、数字和下划线_及破折号-',
'tempid.activeUrl' => 'tempid不是有效的域名或者IP',
'tempid.url' => 'tempid不是有效的URL地址',
'tempid.ip' => 'tempid不是有效的IP地址',
'tempid.length' => 'tempid长度不符',
'tempid.max' => 'tempid超出最大长度',
'tempid.min' => 'tempid低于最小长度',
'tempname.require' => 'tempname不能为空',
'tempname.number' => 'tempname不是数字',
'tempname.float' => 'tempname不是小数',
'tempname.boolean' => 'tempname不是布尔值',
'tempname.email' => 'tempname不是邮箱地址',
'tempname.array' => 'tempname不是数组',
'tempname.accepted' => 'tempname请确认',
'tempname.date' => 'tempname不是有效日期',
'tempname.alpha' => 'tempname不是字母',
'tempname.alphaNum' => 'tempname不是字母和数字',
'tempname.alphaDash' => 'tempname不是字母和数字和下划线及破折号',
'tempname.chs' => 'tempname只能是汉字',
'tempname.chsAlpha' => 'tempname只能是汉字、字母',
'tempname.chsAlphaNum' => 'tempname只能是汉字、字母和数字',
'tempname.chsDash' => 'tempname只能是汉字、字母、数字和下划线_及破折号-',
'tempname.activeUrl' => 'tempname不是有效的域名或者IP',
'tempname.url' => 'tempname不是有效的URL地址',
'tempname.ip' => 'tempname不是有效的IP地址',
'tempname.length' => 'tempname长度不符',
'tempname.max' => 'tempname超出最大长度',
'tempname.min' => 'tempname低于最小长度',
'temptext.require' => 'temptext不能为空',
'temptext.number' => 'temptext不是数字',
'temptext.float' => 'temptext不是小数',
'temptext.boolean' => 'temptext不是布尔值',
'temptext.email' => 'temptext不是邮箱地址',
'temptext.array' => 'temptext不是数组',
'temptext.accepted' => 'temptext请确认',
'temptext.date' => 'temptext不是有效日期',
'temptext.alpha' => 'temptext不是字母',
'temptext.alphaNum' => 'temptext不是字母和数字',
'temptext.alphaDash' => 'temptext不是字母和数字和下划线及破折号',
'temptext.chs' => 'temptext只能是汉字',
'temptext.chsAlpha' => 'temptext只能是汉字、字母',
'temptext.chsAlphaNum' => 'temptext只能是汉字、字母和数字',
'temptext.chsDash' => 'temptext只能是汉字、字母、数字和下划线_及破折号-',
'temptext.activeUrl' => 'temptext不是有效的域名或者IP',
'temptext.url' => 'temptext不是有效的URL地址',
'temptext.ip' => 'temptext不是有效的IP地址',
'temptext.length' => 'temptext长度不符',
'temptext.max' => 'temptext超出最大长度',
'temptext.min' => 'temptext低于最小长度',
'isdefault.require' => 'isdefault不能为空',
'isdefault.number' => 'isdefault不是数字',
'isdefault.float' => 'isdefault不是小数',
'isdefault.boolean' => 'isdefault不是布尔值',
'isdefault.email' => 'isdefault不是邮箱地址',
'isdefault.array' => 'isdefault不是数组',
'isdefault.accepted' => 'isdefault请确认',
'isdefault.date' => 'isdefault不是有效日期',
'isdefault.alpha' => 'isdefault不是字母',
'isdefault.alphaNum' => 'isdefault不是字母和数字',
'isdefault.alphaDash' => 'isdefault不是字母和数字和下划线及破折号',
'isdefault.chs' => 'isdefault只能是汉字',
'isdefault.chsAlpha' => 'isdefault只能是汉字、字母',
'isdefault.chsAlphaNum' => 'isdefault只能是汉字、字母和数字',
'isdefault.chsDash' => 'isdefault只能是汉字、字母、数字和下划线_及破折号-',
'isdefault.activeUrl' => 'isdefault不是有效的域名或者IP',
'isdefault.url' => 'isdefault不是有效的URL地址',
'isdefault.ip' => 'isdefault不是有效的IP地址',
'isdefault.length' => 'isdefault长度不符',
'isdefault.max' => 'isdefault超出最大长度',
'isdefault.min' => 'isdefault低于最小长度',
'showdate.require' => 'showdate不能为空',
'showdate.number' => 'showdate不是数字',
'showdate.float' => 'showdate不是小数',
'showdate.boolean' => 'showdate不是布尔值',
'showdate.email' => 'showdate不是邮箱地址',
'showdate.array' => 'showdate不是数组',
'showdate.accepted' => 'showdate请确认',
'showdate.date' => 'showdate不是有效日期',
'showdate.alpha' => 'showdate不是字母',
'showdate.alphaNum' => 'showdate不是字母和数字',
'showdate.alphaDash' => 'showdate不是字母和数字和下划线及破折号',
'showdate.chs' => 'showdate只能是汉字',
'showdate.chsAlpha' => 'showdate只能是汉字、字母',
'showdate.chsAlphaNum' => 'showdate只能是汉字、字母和数字',
'showdate.chsDash' => 'showdate只能是汉字、字母、数字和下划线_及破折号-',
'showdate.activeUrl' => 'showdate不是有效的域名或者IP',
'showdate.url' => 'showdate不是有效的URL地址',
'showdate.ip' => 'showdate不是有效的IP地址',
'showdate.length' => 'showdate长度不符',
'showdate.max' => 'showdate超出最大长度',
'showdate.min' => 'showdate低于最小长度',
'modid.require' => 'modid不能为空',
'modid.number' => 'modid不是数字',
'modid.float' => 'modid不是小数',
'modid.boolean' => 'modid不是布尔值',
'modid.email' => 'modid不是邮箱地址',
'modid.array' => 'modid不是数组',
'modid.accepted' => 'modid请确认',
'modid.date' => 'modid不是有效日期',
'modid.alpha' => 'modid不是字母',
'modid.alphaNum' => 'modid不是字母和数字',
'modid.alphaDash' => 'modid不是字母和数字和下划线及破折号',
'modid.chs' => 'modid只能是汉字',
'modid.chsAlpha' => 'modid只能是汉字、字母',
'modid.chsAlphaNum' => 'modid只能是汉字、字母和数字',
'modid.chsDash' => 'modid只能是汉字、字母、数字和下划线_及破折号-',
'modid.activeUrl' => 'modid不是有效的域名或者IP',
'modid.url' => 'modid不是有效的URL地址',
'modid.ip' => 'modid不是有效的IP地址',
'modid.length' => 'modid长度不符',
'modid.max' => 'modid超出最大长度',
'modid.min' => 'modid低于最小长度',
];

protected $scene =   [
    'add'=>['tempid','tempname','temptext','isdefault','showdate','modid',],
    'edit'=>['tempid','tempname','temptext','isdefault','showdate','modid',],
    'ck_id'=>['id']
];

}
