<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsuserjs extends Validate{

protected $rule =   [
        'jsid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'jsname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'jssql' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'jstempid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'jsfilename' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'classid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'jsid.require' => 'jsid不能为空',
'jsid.number' => 'jsid不是数字',
'jsid.float' => 'jsid不是小数',
'jsid.boolean' => 'jsid不是布尔值',
'jsid.email' => 'jsid不是邮箱地址',
'jsid.array' => 'jsid不是数组',
'jsid.accepted' => 'jsid请确认',
'jsid.date' => 'jsid不是有效日期',
'jsid.alpha' => 'jsid不是字母',
'jsid.alphaNum' => 'jsid不是字母和数字',
'jsid.alphaDash' => 'jsid不是字母和数字和下划线及破折号',
'jsid.chs' => 'jsid只能是汉字',
'jsid.chsAlpha' => 'jsid只能是汉字、字母',
'jsid.chsAlphaNum' => 'jsid只能是汉字、字母和数字',
'jsid.chsDash' => 'jsid只能是汉字、字母、数字和下划线_及破折号-',
'jsid.activeUrl' => 'jsid不是有效的域名或者IP',
'jsid.url' => 'jsid不是有效的URL地址',
'jsid.ip' => 'jsid不是有效的IP地址',
'jsid.length' => 'jsid长度不符',
'jsid.max' => 'jsid超出最大长度',
'jsid.min' => 'jsid低于最小长度',
'jsname.require' => 'jsname不能为空',
'jsname.number' => 'jsname不是数字',
'jsname.float' => 'jsname不是小数',
'jsname.boolean' => 'jsname不是布尔值',
'jsname.email' => 'jsname不是邮箱地址',
'jsname.array' => 'jsname不是数组',
'jsname.accepted' => 'jsname请确认',
'jsname.date' => 'jsname不是有效日期',
'jsname.alpha' => 'jsname不是字母',
'jsname.alphaNum' => 'jsname不是字母和数字',
'jsname.alphaDash' => 'jsname不是字母和数字和下划线及破折号',
'jsname.chs' => 'jsname只能是汉字',
'jsname.chsAlpha' => 'jsname只能是汉字、字母',
'jsname.chsAlphaNum' => 'jsname只能是汉字、字母和数字',
'jsname.chsDash' => 'jsname只能是汉字、字母、数字和下划线_及破折号-',
'jsname.activeUrl' => 'jsname不是有效的域名或者IP',
'jsname.url' => 'jsname不是有效的URL地址',
'jsname.ip' => 'jsname不是有效的IP地址',
'jsname.length' => 'jsname长度不符',
'jsname.max' => 'jsname超出最大长度',
'jsname.min' => 'jsname低于最小长度',
'jssql.require' => 'jssql不能为空',
'jssql.number' => 'jssql不是数字',
'jssql.float' => 'jssql不是小数',
'jssql.boolean' => 'jssql不是布尔值',
'jssql.email' => 'jssql不是邮箱地址',
'jssql.array' => 'jssql不是数组',
'jssql.accepted' => 'jssql请确认',
'jssql.date' => 'jssql不是有效日期',
'jssql.alpha' => 'jssql不是字母',
'jssql.alphaNum' => 'jssql不是字母和数字',
'jssql.alphaDash' => 'jssql不是字母和数字和下划线及破折号',
'jssql.chs' => 'jssql只能是汉字',
'jssql.chsAlpha' => 'jssql只能是汉字、字母',
'jssql.chsAlphaNum' => 'jssql只能是汉字、字母和数字',
'jssql.chsDash' => 'jssql只能是汉字、字母、数字和下划线_及破折号-',
'jssql.activeUrl' => 'jssql不是有效的域名或者IP',
'jssql.url' => 'jssql不是有效的URL地址',
'jssql.ip' => 'jssql不是有效的IP地址',
'jssql.length' => 'jssql长度不符',
'jssql.max' => 'jssql超出最大长度',
'jssql.min' => 'jssql低于最小长度',
'jstempid.require' => 'jstempid不能为空',
'jstempid.number' => 'jstempid不是数字',
'jstempid.float' => 'jstempid不是小数',
'jstempid.boolean' => 'jstempid不是布尔值',
'jstempid.email' => 'jstempid不是邮箱地址',
'jstempid.array' => 'jstempid不是数组',
'jstempid.accepted' => 'jstempid请确认',
'jstempid.date' => 'jstempid不是有效日期',
'jstempid.alpha' => 'jstempid不是字母',
'jstempid.alphaNum' => 'jstempid不是字母和数字',
'jstempid.alphaDash' => 'jstempid不是字母和数字和下划线及破折号',
'jstempid.chs' => 'jstempid只能是汉字',
'jstempid.chsAlpha' => 'jstempid只能是汉字、字母',
'jstempid.chsAlphaNum' => 'jstempid只能是汉字、字母和数字',
'jstempid.chsDash' => 'jstempid只能是汉字、字母、数字和下划线_及破折号-',
'jstempid.activeUrl' => 'jstempid不是有效的域名或者IP',
'jstempid.url' => 'jstempid不是有效的URL地址',
'jstempid.ip' => 'jstempid不是有效的IP地址',
'jstempid.length' => 'jstempid长度不符',
'jstempid.max' => 'jstempid超出最大长度',
'jstempid.min' => 'jstempid低于最小长度',
'jsfilename.require' => 'jsfilename不能为空',
'jsfilename.number' => 'jsfilename不是数字',
'jsfilename.float' => 'jsfilename不是小数',
'jsfilename.boolean' => 'jsfilename不是布尔值',
'jsfilename.email' => 'jsfilename不是邮箱地址',
'jsfilename.array' => 'jsfilename不是数组',
'jsfilename.accepted' => 'jsfilename请确认',
'jsfilename.date' => 'jsfilename不是有效日期',
'jsfilename.alpha' => 'jsfilename不是字母',
'jsfilename.alphaNum' => 'jsfilename不是字母和数字',
'jsfilename.alphaDash' => 'jsfilename不是字母和数字和下划线及破折号',
'jsfilename.chs' => 'jsfilename只能是汉字',
'jsfilename.chsAlpha' => 'jsfilename只能是汉字、字母',
'jsfilename.chsAlphaNum' => 'jsfilename只能是汉字、字母和数字',
'jsfilename.chsDash' => 'jsfilename只能是汉字、字母、数字和下划线_及破折号-',
'jsfilename.activeUrl' => 'jsfilename不是有效的域名或者IP',
'jsfilename.url' => 'jsfilename不是有效的URL地址',
'jsfilename.ip' => 'jsfilename不是有效的IP地址',
'jsfilename.length' => 'jsfilename长度不符',
'jsfilename.max' => 'jsfilename超出最大长度',
'jsfilename.min' => 'jsfilename低于最小长度',
'classid.require' => 'classid不能为空',
'classid.number' => 'classid不是数字',
'classid.float' => 'classid不是小数',
'classid.boolean' => 'classid不是布尔值',
'classid.email' => 'classid不是邮箱地址',
'classid.array' => 'classid不是数组',
'classid.accepted' => 'classid请确认',
'classid.date' => 'classid不是有效日期',
'classid.alpha' => 'classid不是字母',
'classid.alphaNum' => 'classid不是字母和数字',
'classid.alphaDash' => 'classid不是字母和数字和下划线及破折号',
'classid.chs' => 'classid只能是汉字',
'classid.chsAlpha' => 'classid只能是汉字、字母',
'classid.chsAlphaNum' => 'classid只能是汉字、字母和数字',
'classid.chsDash' => 'classid只能是汉字、字母、数字和下划线_及破折号-',
'classid.activeUrl' => 'classid不是有效的域名或者IP',
'classid.url' => 'classid不是有效的URL地址',
'classid.ip' => 'classid不是有效的IP地址',
'classid.length' => 'classid长度不符',
'classid.max' => 'classid超出最大长度',
'classid.min' => 'classid低于最小长度',
];

protected $scene =   [
    'add'=>['jsid','jsname','jssql','jstempid','jsfilename','classid',],
    'edit'=>['jsid','jsname','jssql','jstempid','jsfilename','classid',],
    'ck_id'=>['id']
];

}
