<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsuseradd extends Validate{

protected $rule =   [
        'userid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'equestion' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'eanswer' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'openip' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'certkey' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'certtime' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'userid.require' => 'userid不能为空',
'userid.number' => 'userid不是数字',
'userid.float' => 'userid不是小数',
'userid.boolean' => 'userid不是布尔值',
'userid.email' => 'userid不是邮箱地址',
'userid.array' => 'userid不是数组',
'userid.accepted' => 'userid请确认',
'userid.date' => 'userid不是有效日期',
'userid.alpha' => 'userid不是字母',
'userid.alphaNum' => 'userid不是字母和数字',
'userid.alphaDash' => 'userid不是字母和数字和下划线及破折号',
'userid.chs' => 'userid只能是汉字',
'userid.chsAlpha' => 'userid只能是汉字、字母',
'userid.chsAlphaNum' => 'userid只能是汉字、字母和数字',
'userid.chsDash' => 'userid只能是汉字、字母、数字和下划线_及破折号-',
'userid.activeUrl' => 'userid不是有效的域名或者IP',
'userid.url' => 'userid不是有效的URL地址',
'userid.ip' => 'userid不是有效的IP地址',
'userid.length' => 'userid长度不符',
'userid.max' => 'userid超出最大长度',
'userid.min' => 'userid低于最小长度',
'equestion.require' => 'equestion不能为空',
'equestion.number' => 'equestion不是数字',
'equestion.float' => 'equestion不是小数',
'equestion.boolean' => 'equestion不是布尔值',
'equestion.email' => 'equestion不是邮箱地址',
'equestion.array' => 'equestion不是数组',
'equestion.accepted' => 'equestion请确认',
'equestion.date' => 'equestion不是有效日期',
'equestion.alpha' => 'equestion不是字母',
'equestion.alphaNum' => 'equestion不是字母和数字',
'equestion.alphaDash' => 'equestion不是字母和数字和下划线及破折号',
'equestion.chs' => 'equestion只能是汉字',
'equestion.chsAlpha' => 'equestion只能是汉字、字母',
'equestion.chsAlphaNum' => 'equestion只能是汉字、字母和数字',
'equestion.chsDash' => 'equestion只能是汉字、字母、数字和下划线_及破折号-',
'equestion.activeUrl' => 'equestion不是有效的域名或者IP',
'equestion.url' => 'equestion不是有效的URL地址',
'equestion.ip' => 'equestion不是有效的IP地址',
'equestion.length' => 'equestion长度不符',
'equestion.max' => 'equestion超出最大长度',
'equestion.min' => 'equestion低于最小长度',
'eanswer.require' => 'eanswer不能为空',
'eanswer.number' => 'eanswer不是数字',
'eanswer.float' => 'eanswer不是小数',
'eanswer.boolean' => 'eanswer不是布尔值',
'eanswer.email' => 'eanswer不是邮箱地址',
'eanswer.array' => 'eanswer不是数组',
'eanswer.accepted' => 'eanswer请确认',
'eanswer.date' => 'eanswer不是有效日期',
'eanswer.alpha' => 'eanswer不是字母',
'eanswer.alphaNum' => 'eanswer不是字母和数字',
'eanswer.alphaDash' => 'eanswer不是字母和数字和下划线及破折号',
'eanswer.chs' => 'eanswer只能是汉字',
'eanswer.chsAlpha' => 'eanswer只能是汉字、字母',
'eanswer.chsAlphaNum' => 'eanswer只能是汉字、字母和数字',
'eanswer.chsDash' => 'eanswer只能是汉字、字母、数字和下划线_及破折号-',
'eanswer.activeUrl' => 'eanswer不是有效的域名或者IP',
'eanswer.url' => 'eanswer不是有效的URL地址',
'eanswer.ip' => 'eanswer不是有效的IP地址',
'eanswer.length' => 'eanswer长度不符',
'eanswer.max' => 'eanswer超出最大长度',
'eanswer.min' => 'eanswer低于最小长度',
'openip.require' => 'openip不能为空',
'openip.number' => 'openip不是数字',
'openip.float' => 'openip不是小数',
'openip.boolean' => 'openip不是布尔值',
'openip.email' => 'openip不是邮箱地址',
'openip.array' => 'openip不是数组',
'openip.accepted' => 'openip请确认',
'openip.date' => 'openip不是有效日期',
'openip.alpha' => 'openip不是字母',
'openip.alphaNum' => 'openip不是字母和数字',
'openip.alphaDash' => 'openip不是字母和数字和下划线及破折号',
'openip.chs' => 'openip只能是汉字',
'openip.chsAlpha' => 'openip只能是汉字、字母',
'openip.chsAlphaNum' => 'openip只能是汉字、字母和数字',
'openip.chsDash' => 'openip只能是汉字、字母、数字和下划线_及破折号-',
'openip.activeUrl' => 'openip不是有效的域名或者IP',
'openip.url' => 'openip不是有效的URL地址',
'openip.ip' => 'openip不是有效的IP地址',
'openip.length' => 'openip长度不符',
'openip.max' => 'openip超出最大长度',
'openip.min' => 'openip低于最小长度',
'certkey.require' => 'certkey不能为空',
'certkey.number' => 'certkey不是数字',
'certkey.float' => 'certkey不是小数',
'certkey.boolean' => 'certkey不是布尔值',
'certkey.email' => 'certkey不是邮箱地址',
'certkey.array' => 'certkey不是数组',
'certkey.accepted' => 'certkey请确认',
'certkey.date' => 'certkey不是有效日期',
'certkey.alpha' => 'certkey不是字母',
'certkey.alphaNum' => 'certkey不是字母和数字',
'certkey.alphaDash' => 'certkey不是字母和数字和下划线及破折号',
'certkey.chs' => 'certkey只能是汉字',
'certkey.chsAlpha' => 'certkey只能是汉字、字母',
'certkey.chsAlphaNum' => 'certkey只能是汉字、字母和数字',
'certkey.chsDash' => 'certkey只能是汉字、字母、数字和下划线_及破折号-',
'certkey.activeUrl' => 'certkey不是有效的域名或者IP',
'certkey.url' => 'certkey不是有效的URL地址',
'certkey.ip' => 'certkey不是有效的IP地址',
'certkey.length' => 'certkey长度不符',
'certkey.max' => 'certkey超出最大长度',
'certkey.min' => 'certkey低于最小长度',
'certtime.require' => 'certtime不能为空',
'certtime.number' => 'certtime不是数字',
'certtime.float' => 'certtime不是小数',
'certtime.boolean' => 'certtime不是布尔值',
'certtime.email' => 'certtime不是邮箱地址',
'certtime.array' => 'certtime不是数组',
'certtime.accepted' => 'certtime请确认',
'certtime.date' => 'certtime不是有效日期',
'certtime.alpha' => 'certtime不是字母',
'certtime.alphaNum' => 'certtime不是字母和数字',
'certtime.alphaDash' => 'certtime不是字母和数字和下划线及破折号',
'certtime.chs' => 'certtime只能是汉字',
'certtime.chsAlpha' => 'certtime只能是汉字、字母',
'certtime.chsAlphaNum' => 'certtime只能是汉字、字母和数字',
'certtime.chsDash' => 'certtime只能是汉字、字母、数字和下划线_及破折号-',
'certtime.activeUrl' => 'certtime不是有效的域名或者IP',
'certtime.url' => 'certtime不是有效的URL地址',
'certtime.ip' => 'certtime不是有效的IP地址',
'certtime.length' => 'certtime长度不符',
'certtime.max' => 'certtime超出最大长度',
'certtime.min' => 'certtime低于最小长度',
];

protected $scene =   [
    'add'=>['userid','equestion','eanswer','openip','certkey','certtime',],
    'edit'=>['userid','equestion','eanswer','openip','certkey','certtime',],
    'ck_id'=>['id']
];

}
