<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsdownurlqz extends Validate{

protected $rule =   [
        'urlid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'urlname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'url' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'downtype' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'urlid.require' => 'urlid不能为空',
'urlid.number' => 'urlid不是数字',
'urlid.float' => 'urlid不是小数',
'urlid.boolean' => 'urlid不是布尔值',
'urlid.email' => 'urlid不是邮箱地址',
'urlid.array' => 'urlid不是数组',
'urlid.accepted' => 'urlid请确认',
'urlid.date' => 'urlid不是有效日期',
'urlid.alpha' => 'urlid不是字母',
'urlid.alphaNum' => 'urlid不是字母和数字',
'urlid.alphaDash' => 'urlid不是字母和数字和下划线及破折号',
'urlid.chs' => 'urlid只能是汉字',
'urlid.chsAlpha' => 'urlid只能是汉字、字母',
'urlid.chsAlphaNum' => 'urlid只能是汉字、字母和数字',
'urlid.chsDash' => 'urlid只能是汉字、字母、数字和下划线_及破折号-',
'urlid.activeUrl' => 'urlid不是有效的域名或者IP',
'urlid.url' => 'urlid不是有效的URL地址',
'urlid.ip' => 'urlid不是有效的IP地址',
'urlid.length' => 'urlid长度不符',
'urlid.max' => 'urlid超出最大长度',
'urlid.min' => 'urlid低于最小长度',
'urlname.require' => 'urlname不能为空',
'urlname.number' => 'urlname不是数字',
'urlname.float' => 'urlname不是小数',
'urlname.boolean' => 'urlname不是布尔值',
'urlname.email' => 'urlname不是邮箱地址',
'urlname.array' => 'urlname不是数组',
'urlname.accepted' => 'urlname请确认',
'urlname.date' => 'urlname不是有效日期',
'urlname.alpha' => 'urlname不是字母',
'urlname.alphaNum' => 'urlname不是字母和数字',
'urlname.alphaDash' => 'urlname不是字母和数字和下划线及破折号',
'urlname.chs' => 'urlname只能是汉字',
'urlname.chsAlpha' => 'urlname只能是汉字、字母',
'urlname.chsAlphaNum' => 'urlname只能是汉字、字母和数字',
'urlname.chsDash' => 'urlname只能是汉字、字母、数字和下划线_及破折号-',
'urlname.activeUrl' => 'urlname不是有效的域名或者IP',
'urlname.url' => 'urlname不是有效的URL地址',
'urlname.ip' => 'urlname不是有效的IP地址',
'urlname.length' => 'urlname长度不符',
'urlname.max' => 'urlname超出最大长度',
'urlname.min' => 'urlname低于最小长度',
'url.require' => 'url不能为空',
'url.number' => 'url不是数字',
'url.float' => 'url不是小数',
'url.boolean' => 'url不是布尔值',
'url.email' => 'url不是邮箱地址',
'url.array' => 'url不是数组',
'url.accepted' => 'url请确认',
'url.date' => 'url不是有效日期',
'url.alpha' => 'url不是字母',
'url.alphaNum' => 'url不是字母和数字',
'url.alphaDash' => 'url不是字母和数字和下划线及破折号',
'url.chs' => 'url只能是汉字',
'url.chsAlpha' => 'url只能是汉字、字母',
'url.chsAlphaNum' => 'url只能是汉字、字母和数字',
'url.chsDash' => 'url只能是汉字、字母、数字和下划线_及破折号-',
'url.activeUrl' => 'url不是有效的域名或者IP',
'url.url' => 'url不是有效的URL地址',
'url.ip' => 'url不是有效的IP地址',
'url.length' => 'url长度不符',
'url.max' => 'url超出最大长度',
'url.min' => 'url低于最小长度',
'downtype.require' => 'downtype不能为空',
'downtype.number' => 'downtype不是数字',
'downtype.float' => 'downtype不是小数',
'downtype.boolean' => 'downtype不是布尔值',
'downtype.email' => 'downtype不是邮箱地址',
'downtype.array' => 'downtype不是数组',
'downtype.accepted' => 'downtype请确认',
'downtype.date' => 'downtype不是有效日期',
'downtype.alpha' => 'downtype不是字母',
'downtype.alphaNum' => 'downtype不是字母和数字',
'downtype.alphaDash' => 'downtype不是字母和数字和下划线及破折号',
'downtype.chs' => 'downtype只能是汉字',
'downtype.chsAlpha' => 'downtype只能是汉字、字母',
'downtype.chsAlphaNum' => 'downtype只能是汉字、字母和数字',
'downtype.chsDash' => 'downtype只能是汉字、字母、数字和下划线_及破折号-',
'downtype.activeUrl' => 'downtype不是有效的域名或者IP',
'downtype.url' => 'downtype不是有效的URL地址',
'downtype.ip' => 'downtype不是有效的IP地址',
'downtype.length' => 'downtype长度不符',
'downtype.max' => 'downtype超出最大长度',
'downtype.min' => 'downtype低于最小长度',
];

protected $scene =   [
    'add'=>['urlid','urlname','url','downtype',],
    'edit'=>['urlid','urlname','url','downtype',],
    'ck_id'=>['id']
];

}
