<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsvglist extends Validate{

protected $rule =   [
        'vgid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'addtime' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'userid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'outtime' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'vgid.require' => 'vgid不能为空',
'vgid.number' => 'vgid不是数字',
'vgid.float' => 'vgid不是小数',
'vgid.boolean' => 'vgid不是布尔值',
'vgid.email' => 'vgid不是邮箱地址',
'vgid.array' => 'vgid不是数组',
'vgid.accepted' => 'vgid请确认',
'vgid.date' => 'vgid不是有效日期',
'vgid.alpha' => 'vgid不是字母',
'vgid.alphaNum' => 'vgid不是字母和数字',
'vgid.alphaDash' => 'vgid不是字母和数字和下划线及破折号',
'vgid.chs' => 'vgid只能是汉字',
'vgid.chsAlpha' => 'vgid只能是汉字、字母',
'vgid.chsAlphaNum' => 'vgid只能是汉字、字母和数字',
'vgid.chsDash' => 'vgid只能是汉字、字母、数字和下划线_及破折号-',
'vgid.activeUrl' => 'vgid不是有效的域名或者IP',
'vgid.url' => 'vgid不是有效的URL地址',
'vgid.ip' => 'vgid不是有效的IP地址',
'vgid.length' => 'vgid长度不符',
'vgid.max' => 'vgid超出最大长度',
'vgid.min' => 'vgid低于最小长度',
'addtime.require' => 'addtime不能为空',
'addtime.number' => 'addtime不是数字',
'addtime.float' => 'addtime不是小数',
'addtime.boolean' => 'addtime不是布尔值',
'addtime.email' => 'addtime不是邮箱地址',
'addtime.array' => 'addtime不是数组',
'addtime.accepted' => 'addtime请确认',
'addtime.date' => 'addtime不是有效日期',
'addtime.alpha' => 'addtime不是字母',
'addtime.alphaNum' => 'addtime不是字母和数字',
'addtime.alphaDash' => 'addtime不是字母和数字和下划线及破折号',
'addtime.chs' => 'addtime只能是汉字',
'addtime.chsAlpha' => 'addtime只能是汉字、字母',
'addtime.chsAlphaNum' => 'addtime只能是汉字、字母和数字',
'addtime.chsDash' => 'addtime只能是汉字、字母、数字和下划线_及破折号-',
'addtime.activeUrl' => 'addtime不是有效的域名或者IP',
'addtime.url' => 'addtime不是有效的URL地址',
'addtime.ip' => 'addtime不是有效的IP地址',
'addtime.length' => 'addtime长度不符',
'addtime.max' => 'addtime超出最大长度',
'addtime.min' => 'addtime低于最小长度',
'userid.require' => 'userid不能为空',
'userid.number' => 'userid不是数字',
'userid.float' => 'userid不是小数',
'userid.boolean' => 'userid不是布尔值',
'userid.email' => 'userid不是邮箱地址',
'userid.array' => 'userid不是数组',
'userid.accepted' => 'userid请确认',
'userid.date' => 'userid不是有效日期',
'userid.alpha' => 'userid不是字母',
'userid.alphaNum' => 'userid不是字母和数字',
'userid.alphaDash' => 'userid不是字母和数字和下划线及破折号',
'userid.chs' => 'userid只能是汉字',
'userid.chsAlpha' => 'userid只能是汉字、字母',
'userid.chsAlphaNum' => 'userid只能是汉字、字母和数字',
'userid.chsDash' => 'userid只能是汉字、字母、数字和下划线_及破折号-',
'userid.activeUrl' => 'userid不是有效的域名或者IP',
'userid.url' => 'userid不是有效的URL地址',
'userid.ip' => 'userid不是有效的IP地址',
'userid.length' => 'userid长度不符',
'userid.max' => 'userid超出最大长度',
'userid.min' => 'userid低于最小长度',
'outtime.require' => 'outtime不能为空',
'outtime.number' => 'outtime不是数字',
'outtime.float' => 'outtime不是小数',
'outtime.boolean' => 'outtime不是布尔值',
'outtime.email' => 'outtime不是邮箱地址',
'outtime.array' => 'outtime不是数组',
'outtime.accepted' => 'outtime请确认',
'outtime.date' => 'outtime不是有效日期',
'outtime.alpha' => 'outtime不是字母',
'outtime.alphaNum' => 'outtime不是字母和数字',
'outtime.alphaDash' => 'outtime不是字母和数字和下划线及破折号',
'outtime.chs' => 'outtime只能是汉字',
'outtime.chsAlpha' => 'outtime只能是汉字、字母',
'outtime.chsAlphaNum' => 'outtime只能是汉字、字母和数字',
'outtime.chsDash' => 'outtime只能是汉字、字母、数字和下划线_及破折号-',
'outtime.activeUrl' => 'outtime不是有效的域名或者IP',
'outtime.url' => 'outtime不是有效的URL地址',
'outtime.ip' => 'outtime不是有效的IP地址',
'outtime.length' => 'outtime长度不符',
'outtime.max' => 'outtime超出最大长度',
'outtime.min' => 'outtime低于最小长度',
];

protected $scene =   [
    'add'=>['vgid','addtime','userid','outtime',],
    'edit'=>['vgid','addtime','userid','outtime',],
    'ck_id'=>['id']
];

}
