<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsclassadd extends Validate{

protected $rule =   [
        'classid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'classtext' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'ttids' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'eclasspagetext' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'classid.require' => 'classid不能为空',
'classid.number' => 'classid不是数字',
'classid.float' => 'classid不是小数',
'classid.boolean' => 'classid不是布尔值',
'classid.email' => 'classid不是邮箱地址',
'classid.array' => 'classid不是数组',
'classid.accepted' => 'classid请确认',
'classid.date' => 'classid不是有效日期',
'classid.alpha' => 'classid不是字母',
'classid.alphaNum' => 'classid不是字母和数字',
'classid.alphaDash' => 'classid不是字母和数字和下划线及破折号',
'classid.chs' => 'classid只能是汉字',
'classid.chsAlpha' => 'classid只能是汉字、字母',
'classid.chsAlphaNum' => 'classid只能是汉字、字母和数字',
'classid.chsDash' => 'classid只能是汉字、字母、数字和下划线_及破折号-',
'classid.activeUrl' => 'classid不是有效的域名或者IP',
'classid.url' => 'classid不是有效的URL地址',
'classid.ip' => 'classid不是有效的IP地址',
'classid.length' => 'classid长度不符',
'classid.max' => 'classid超出最大长度',
'classid.min' => 'classid低于最小长度',
'classtext.require' => 'classtext不能为空',
'classtext.number' => 'classtext不是数字',
'classtext.float' => 'classtext不是小数',
'classtext.boolean' => 'classtext不是布尔值',
'classtext.email' => 'classtext不是邮箱地址',
'classtext.array' => 'classtext不是数组',
'classtext.accepted' => 'classtext请确认',
'classtext.date' => 'classtext不是有效日期',
'classtext.alpha' => 'classtext不是字母',
'classtext.alphaNum' => 'classtext不是字母和数字',
'classtext.alphaDash' => 'classtext不是字母和数字和下划线及破折号',
'classtext.chs' => 'classtext只能是汉字',
'classtext.chsAlpha' => 'classtext只能是汉字、字母',
'classtext.chsAlphaNum' => 'classtext只能是汉字、字母和数字',
'classtext.chsDash' => 'classtext只能是汉字、字母、数字和下划线_及破折号-',
'classtext.activeUrl' => 'classtext不是有效的域名或者IP',
'classtext.url' => 'classtext不是有效的URL地址',
'classtext.ip' => 'classtext不是有效的IP地址',
'classtext.length' => 'classtext长度不符',
'classtext.max' => 'classtext超出最大长度',
'classtext.min' => 'classtext低于最小长度',
'ttids.require' => 'ttids不能为空',
'ttids.number' => 'ttids不是数字',
'ttids.float' => 'ttids不是小数',
'ttids.boolean' => 'ttids不是布尔值',
'ttids.email' => 'ttids不是邮箱地址',
'ttids.array' => 'ttids不是数组',
'ttids.accepted' => 'ttids请确认',
'ttids.date' => 'ttids不是有效日期',
'ttids.alpha' => 'ttids不是字母',
'ttids.alphaNum' => 'ttids不是字母和数字',
'ttids.alphaDash' => 'ttids不是字母和数字和下划线及破折号',
'ttids.chs' => 'ttids只能是汉字',
'ttids.chsAlpha' => 'ttids只能是汉字、字母',
'ttids.chsAlphaNum' => 'ttids只能是汉字、字母和数字',
'ttids.chsDash' => 'ttids只能是汉字、字母、数字和下划线_及破折号-',
'ttids.activeUrl' => 'ttids不是有效的域名或者IP',
'ttids.url' => 'ttids不是有效的URL地址',
'ttids.ip' => 'ttids不是有效的IP地址',
'ttids.length' => 'ttids长度不符',
'ttids.max' => 'ttids超出最大长度',
'ttids.min' => 'ttids低于最小长度',
'eclasspagetext.require' => 'eclasspagetext不能为空',
'eclasspagetext.number' => 'eclasspagetext不是数字',
'eclasspagetext.float' => 'eclasspagetext不是小数',
'eclasspagetext.boolean' => 'eclasspagetext不是布尔值',
'eclasspagetext.email' => 'eclasspagetext不是邮箱地址',
'eclasspagetext.array' => 'eclasspagetext不是数组',
'eclasspagetext.accepted' => 'eclasspagetext请确认',
'eclasspagetext.date' => 'eclasspagetext不是有效日期',
'eclasspagetext.alpha' => 'eclasspagetext不是字母',
'eclasspagetext.alphaNum' => 'eclasspagetext不是字母和数字',
'eclasspagetext.alphaDash' => 'eclasspagetext不是字母和数字和下划线及破折号',
'eclasspagetext.chs' => 'eclasspagetext只能是汉字',
'eclasspagetext.chsAlpha' => 'eclasspagetext只能是汉字、字母',
'eclasspagetext.chsAlphaNum' => 'eclasspagetext只能是汉字、字母和数字',
'eclasspagetext.chsDash' => 'eclasspagetext只能是汉字、字母、数字和下划线_及破折号-',
'eclasspagetext.activeUrl' => 'eclasspagetext不是有效的域名或者IP',
'eclasspagetext.url' => 'eclasspagetext不是有效的URL地址',
'eclasspagetext.ip' => 'eclasspagetext不是有效的IP地址',
'eclasspagetext.length' => 'eclasspagetext长度不符',
'eclasspagetext.max' => 'eclasspagetext超出最大长度',
'eclasspagetext.min' => 'eclasspagetext低于最小长度',
];

protected $scene =   [
    'add'=>['classid','classtext','ttids','eclasspagetext',],
    'edit'=>['classid','classtext','ttids','eclasspagetext',],
    'ck_id'=>['id']
];

}
