<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsmenu extends Validate{

protected $rule =   [
        'menuid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'menuname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'menuurl' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'myorder' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'classid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'addhash' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'menuid.require' => 'menuid不能为空',
'menuid.number' => 'menuid不是数字',
'menuid.float' => 'menuid不是小数',
'menuid.boolean' => 'menuid不是布尔值',
'menuid.email' => 'menuid不是邮箱地址',
'menuid.array' => 'menuid不是数组',
'menuid.accepted' => 'menuid请确认',
'menuid.date' => 'menuid不是有效日期',
'menuid.alpha' => 'menuid不是字母',
'menuid.alphaNum' => 'menuid不是字母和数字',
'menuid.alphaDash' => 'menuid不是字母和数字和下划线及破折号',
'menuid.chs' => 'menuid只能是汉字',
'menuid.chsAlpha' => 'menuid只能是汉字、字母',
'menuid.chsAlphaNum' => 'menuid只能是汉字、字母和数字',
'menuid.chsDash' => 'menuid只能是汉字、字母、数字和下划线_及破折号-',
'menuid.activeUrl' => 'menuid不是有效的域名或者IP',
'menuid.url' => 'menuid不是有效的URL地址',
'menuid.ip' => 'menuid不是有效的IP地址',
'menuid.length' => 'menuid长度不符',
'menuid.max' => 'menuid超出最大长度',
'menuid.min' => 'menuid低于最小长度',
'menuname.require' => 'menuname不能为空',
'menuname.number' => 'menuname不是数字',
'menuname.float' => 'menuname不是小数',
'menuname.boolean' => 'menuname不是布尔值',
'menuname.email' => 'menuname不是邮箱地址',
'menuname.array' => 'menuname不是数组',
'menuname.accepted' => 'menuname请确认',
'menuname.date' => 'menuname不是有效日期',
'menuname.alpha' => 'menuname不是字母',
'menuname.alphaNum' => 'menuname不是字母和数字',
'menuname.alphaDash' => 'menuname不是字母和数字和下划线及破折号',
'menuname.chs' => 'menuname只能是汉字',
'menuname.chsAlpha' => 'menuname只能是汉字、字母',
'menuname.chsAlphaNum' => 'menuname只能是汉字、字母和数字',
'menuname.chsDash' => 'menuname只能是汉字、字母、数字和下划线_及破折号-',
'menuname.activeUrl' => 'menuname不是有效的域名或者IP',
'menuname.url' => 'menuname不是有效的URL地址',
'menuname.ip' => 'menuname不是有效的IP地址',
'menuname.length' => 'menuname长度不符',
'menuname.max' => 'menuname超出最大长度',
'menuname.min' => 'menuname低于最小长度',
'menuurl.require' => 'menuurl不能为空',
'menuurl.number' => 'menuurl不是数字',
'menuurl.float' => 'menuurl不是小数',
'menuurl.boolean' => 'menuurl不是布尔值',
'menuurl.email' => 'menuurl不是邮箱地址',
'menuurl.array' => 'menuurl不是数组',
'menuurl.accepted' => 'menuurl请确认',
'menuurl.date' => 'menuurl不是有效日期',
'menuurl.alpha' => 'menuurl不是字母',
'menuurl.alphaNum' => 'menuurl不是字母和数字',
'menuurl.alphaDash' => 'menuurl不是字母和数字和下划线及破折号',
'menuurl.chs' => 'menuurl只能是汉字',
'menuurl.chsAlpha' => 'menuurl只能是汉字、字母',
'menuurl.chsAlphaNum' => 'menuurl只能是汉字、字母和数字',
'menuurl.chsDash' => 'menuurl只能是汉字、字母、数字和下划线_及破折号-',
'menuurl.activeUrl' => 'menuurl不是有效的域名或者IP',
'menuurl.url' => 'menuurl不是有效的URL地址',
'menuurl.ip' => 'menuurl不是有效的IP地址',
'menuurl.length' => 'menuurl长度不符',
'menuurl.max' => 'menuurl超出最大长度',
'menuurl.min' => 'menuurl低于最小长度',
'myorder.require' => 'myorder不能为空',
'myorder.number' => 'myorder不是数字',
'myorder.float' => 'myorder不是小数',
'myorder.boolean' => 'myorder不是布尔值',
'myorder.email' => 'myorder不是邮箱地址',
'myorder.array' => 'myorder不是数组',
'myorder.accepted' => 'myorder请确认',
'myorder.date' => 'myorder不是有效日期',
'myorder.alpha' => 'myorder不是字母',
'myorder.alphaNum' => 'myorder不是字母和数字',
'myorder.alphaDash' => 'myorder不是字母和数字和下划线及破折号',
'myorder.chs' => 'myorder只能是汉字',
'myorder.chsAlpha' => 'myorder只能是汉字、字母',
'myorder.chsAlphaNum' => 'myorder只能是汉字、字母和数字',
'myorder.chsDash' => 'myorder只能是汉字、字母、数字和下划线_及破折号-',
'myorder.activeUrl' => 'myorder不是有效的域名或者IP',
'myorder.url' => 'myorder不是有效的URL地址',
'myorder.ip' => 'myorder不是有效的IP地址',
'myorder.length' => 'myorder长度不符',
'myorder.max' => 'myorder超出最大长度',
'myorder.min' => 'myorder低于最小长度',
'classid.require' => 'classid不能为空',
'classid.number' => 'classid不是数字',
'classid.float' => 'classid不是小数',
'classid.boolean' => 'classid不是布尔值',
'classid.email' => 'classid不是邮箱地址',
'classid.array' => 'classid不是数组',
'classid.accepted' => 'classid请确认',
'classid.date' => 'classid不是有效日期',
'classid.alpha' => 'classid不是字母',
'classid.alphaNum' => 'classid不是字母和数字',
'classid.alphaDash' => 'classid不是字母和数字和下划线及破折号',
'classid.chs' => 'classid只能是汉字',
'classid.chsAlpha' => 'classid只能是汉字、字母',
'classid.chsAlphaNum' => 'classid只能是汉字、字母和数字',
'classid.chsDash' => 'classid只能是汉字、字母、数字和下划线_及破折号-',
'classid.activeUrl' => 'classid不是有效的域名或者IP',
'classid.url' => 'classid不是有效的URL地址',
'classid.ip' => 'classid不是有效的IP地址',
'classid.length' => 'classid长度不符',
'classid.max' => 'classid超出最大长度',
'classid.min' => 'classid低于最小长度',
'addhash.require' => 'addhash不能为空',
'addhash.number' => 'addhash不是数字',
'addhash.float' => 'addhash不是小数',
'addhash.boolean' => 'addhash不是布尔值',
'addhash.email' => 'addhash不是邮箱地址',
'addhash.array' => 'addhash不是数组',
'addhash.accepted' => 'addhash请确认',
'addhash.date' => 'addhash不是有效日期',
'addhash.alpha' => 'addhash不是字母',
'addhash.alphaNum' => 'addhash不是字母和数字',
'addhash.alphaDash' => 'addhash不是字母和数字和下划线及破折号',
'addhash.chs' => 'addhash只能是汉字',
'addhash.chsAlpha' => 'addhash只能是汉字、字母',
'addhash.chsAlphaNum' => 'addhash只能是汉字、字母和数字',
'addhash.chsDash' => 'addhash只能是汉字、字母、数字和下划线_及破折号-',
'addhash.activeUrl' => 'addhash不是有效的域名或者IP',
'addhash.url' => 'addhash不是有效的URL地址',
'addhash.ip' => 'addhash不是有效的IP地址',
'addhash.length' => 'addhash长度不符',
'addhash.max' => 'addhash超出最大长度',
'addhash.min' => 'addhash低于最小长度',
];

protected $scene =   [
    'add'=>['menuid','menuname','menuurl','myorder','classid','addhash',],
    'edit'=>['menuid','menuname','menuurl','myorder','classid','addhash',],
    'ck_id'=>['id']
];

}
