<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewshy extends Validate{

protected $rule =   [
        'fid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'userid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'fname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'cid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'fsay' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'fid.require' => 'fid不能为空',
'fid.number' => 'fid不是数字',
'fid.float' => 'fid不是小数',
'fid.boolean' => 'fid不是布尔值',
'fid.email' => 'fid不是邮箱地址',
'fid.array' => 'fid不是数组',
'fid.accepted' => 'fid请确认',
'fid.date' => 'fid不是有效日期',
'fid.alpha' => 'fid不是字母',
'fid.alphaNum' => 'fid不是字母和数字',
'fid.alphaDash' => 'fid不是字母和数字和下划线及破折号',
'fid.chs' => 'fid只能是汉字',
'fid.chsAlpha' => 'fid只能是汉字、字母',
'fid.chsAlphaNum' => 'fid只能是汉字、字母和数字',
'fid.chsDash' => 'fid只能是汉字、字母、数字和下划线_及破折号-',
'fid.activeUrl' => 'fid不是有效的域名或者IP',
'fid.url' => 'fid不是有效的URL地址',
'fid.ip' => 'fid不是有效的IP地址',
'fid.length' => 'fid长度不符',
'fid.max' => 'fid超出最大长度',
'fid.min' => 'fid低于最小长度',
'userid.require' => 'userid不能为空',
'userid.number' => 'userid不是数字',
'userid.float' => 'userid不是小数',
'userid.boolean' => 'userid不是布尔值',
'userid.email' => 'userid不是邮箱地址',
'userid.array' => 'userid不是数组',
'userid.accepted' => 'userid请确认',
'userid.date' => 'userid不是有效日期',
'userid.alpha' => 'userid不是字母',
'userid.alphaNum' => 'userid不是字母和数字',
'userid.alphaDash' => 'userid不是字母和数字和下划线及破折号',
'userid.chs' => 'userid只能是汉字',
'userid.chsAlpha' => 'userid只能是汉字、字母',
'userid.chsAlphaNum' => 'userid只能是汉字、字母和数字',
'userid.chsDash' => 'userid只能是汉字、字母、数字和下划线_及破折号-',
'userid.activeUrl' => 'userid不是有效的域名或者IP',
'userid.url' => 'userid不是有效的URL地址',
'userid.ip' => 'userid不是有效的IP地址',
'userid.length' => 'userid长度不符',
'userid.max' => 'userid超出最大长度',
'userid.min' => 'userid低于最小长度',
'fname.require' => 'fname不能为空',
'fname.number' => 'fname不是数字',
'fname.float' => 'fname不是小数',
'fname.boolean' => 'fname不是布尔值',
'fname.email' => 'fname不是邮箱地址',
'fname.array' => 'fname不是数组',
'fname.accepted' => 'fname请确认',
'fname.date' => 'fname不是有效日期',
'fname.alpha' => 'fname不是字母',
'fname.alphaNum' => 'fname不是字母和数字',
'fname.alphaDash' => 'fname不是字母和数字和下划线及破折号',
'fname.chs' => 'fname只能是汉字',
'fname.chsAlpha' => 'fname只能是汉字、字母',
'fname.chsAlphaNum' => 'fname只能是汉字、字母和数字',
'fname.chsDash' => 'fname只能是汉字、字母、数字和下划线_及破折号-',
'fname.activeUrl' => 'fname不是有效的域名或者IP',
'fname.url' => 'fname不是有效的URL地址',
'fname.ip' => 'fname不是有效的IP地址',
'fname.length' => 'fname长度不符',
'fname.max' => 'fname超出最大长度',
'fname.min' => 'fname低于最小长度',
'cid.require' => 'cid不能为空',
'cid.number' => 'cid不是数字',
'cid.float' => 'cid不是小数',
'cid.boolean' => 'cid不是布尔值',
'cid.email' => 'cid不是邮箱地址',
'cid.array' => 'cid不是数组',
'cid.accepted' => 'cid请确认',
'cid.date' => 'cid不是有效日期',
'cid.alpha' => 'cid不是字母',
'cid.alphaNum' => 'cid不是字母和数字',
'cid.alphaDash' => 'cid不是字母和数字和下划线及破折号',
'cid.chs' => 'cid只能是汉字',
'cid.chsAlpha' => 'cid只能是汉字、字母',
'cid.chsAlphaNum' => 'cid只能是汉字、字母和数字',
'cid.chsDash' => 'cid只能是汉字、字母、数字和下划线_及破折号-',
'cid.activeUrl' => 'cid不是有效的域名或者IP',
'cid.url' => 'cid不是有效的URL地址',
'cid.ip' => 'cid不是有效的IP地址',
'cid.length' => 'cid长度不符',
'cid.max' => 'cid超出最大长度',
'cid.min' => 'cid低于最小长度',
'fsay.require' => 'fsay不能为空',
'fsay.number' => 'fsay不是数字',
'fsay.float' => 'fsay不是小数',
'fsay.boolean' => 'fsay不是布尔值',
'fsay.email' => 'fsay不是邮箱地址',
'fsay.array' => 'fsay不是数组',
'fsay.accepted' => 'fsay请确认',
'fsay.date' => 'fsay不是有效日期',
'fsay.alpha' => 'fsay不是字母',
'fsay.alphaNum' => 'fsay不是字母和数字',
'fsay.alphaDash' => 'fsay不是字母和数字和下划线及破折号',
'fsay.chs' => 'fsay只能是汉字',
'fsay.chsAlpha' => 'fsay只能是汉字、字母',
'fsay.chsAlphaNum' => 'fsay只能是汉字、字母和数字',
'fsay.chsDash' => 'fsay只能是汉字、字母、数字和下划线_及破折号-',
'fsay.activeUrl' => 'fsay不是有效的域名或者IP',
'fsay.url' => 'fsay不是有效的URL地址',
'fsay.ip' => 'fsay不是有效的IP地址',
'fsay.length' => 'fsay长度不符',
'fsay.max' => 'fsay超出最大长度',
'fsay.min' => 'fsay低于最小长度',
];

protected $scene =   [
    'add'=>['fid','userid','fname','cid','fsay',],
    'edit'=>['fid','userid','fname','cid','fsay',],
    'ck_id'=>['id']
];

}
