<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsmenuclass extends Validate{

protected $rule =   [
        'classid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'classname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'issys' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'myorder' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'classtype' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'groupids' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'classid.require' => 'classid不能为空',
'classid.number' => 'classid不是数字',
'classid.float' => 'classid不是小数',
'classid.boolean' => 'classid不是布尔值',
'classid.email' => 'classid不是邮箱地址',
'classid.array' => 'classid不是数组',
'classid.accepted' => 'classid请确认',
'classid.date' => 'classid不是有效日期',
'classid.alpha' => 'classid不是字母',
'classid.alphaNum' => 'classid不是字母和数字',
'classid.alphaDash' => 'classid不是字母和数字和下划线及破折号',
'classid.chs' => 'classid只能是汉字',
'classid.chsAlpha' => 'classid只能是汉字、字母',
'classid.chsAlphaNum' => 'classid只能是汉字、字母和数字',
'classid.chsDash' => 'classid只能是汉字、字母、数字和下划线_及破折号-',
'classid.activeUrl' => 'classid不是有效的域名或者IP',
'classid.url' => 'classid不是有效的URL地址',
'classid.ip' => 'classid不是有效的IP地址',
'classid.length' => 'classid长度不符',
'classid.max' => 'classid超出最大长度',
'classid.min' => 'classid低于最小长度',
'classname.require' => 'classname不能为空',
'classname.number' => 'classname不是数字',
'classname.float' => 'classname不是小数',
'classname.boolean' => 'classname不是布尔值',
'classname.email' => 'classname不是邮箱地址',
'classname.array' => 'classname不是数组',
'classname.accepted' => 'classname请确认',
'classname.date' => 'classname不是有效日期',
'classname.alpha' => 'classname不是字母',
'classname.alphaNum' => 'classname不是字母和数字',
'classname.alphaDash' => 'classname不是字母和数字和下划线及破折号',
'classname.chs' => 'classname只能是汉字',
'classname.chsAlpha' => 'classname只能是汉字、字母',
'classname.chsAlphaNum' => 'classname只能是汉字、字母和数字',
'classname.chsDash' => 'classname只能是汉字、字母、数字和下划线_及破折号-',
'classname.activeUrl' => 'classname不是有效的域名或者IP',
'classname.url' => 'classname不是有效的URL地址',
'classname.ip' => 'classname不是有效的IP地址',
'classname.length' => 'classname长度不符',
'classname.max' => 'classname超出最大长度',
'classname.min' => 'classname低于最小长度',
'issys.require' => 'issys不能为空',
'issys.number' => 'issys不是数字',
'issys.float' => 'issys不是小数',
'issys.boolean' => 'issys不是布尔值',
'issys.email' => 'issys不是邮箱地址',
'issys.array' => 'issys不是数组',
'issys.accepted' => 'issys请确认',
'issys.date' => 'issys不是有效日期',
'issys.alpha' => 'issys不是字母',
'issys.alphaNum' => 'issys不是字母和数字',
'issys.alphaDash' => 'issys不是字母和数字和下划线及破折号',
'issys.chs' => 'issys只能是汉字',
'issys.chsAlpha' => 'issys只能是汉字、字母',
'issys.chsAlphaNum' => 'issys只能是汉字、字母和数字',
'issys.chsDash' => 'issys只能是汉字、字母、数字和下划线_及破折号-',
'issys.activeUrl' => 'issys不是有效的域名或者IP',
'issys.url' => 'issys不是有效的URL地址',
'issys.ip' => 'issys不是有效的IP地址',
'issys.length' => 'issys长度不符',
'issys.max' => 'issys超出最大长度',
'issys.min' => 'issys低于最小长度',
'myorder.require' => 'myorder不能为空',
'myorder.number' => 'myorder不是数字',
'myorder.float' => 'myorder不是小数',
'myorder.boolean' => 'myorder不是布尔值',
'myorder.email' => 'myorder不是邮箱地址',
'myorder.array' => 'myorder不是数组',
'myorder.accepted' => 'myorder请确认',
'myorder.date' => 'myorder不是有效日期',
'myorder.alpha' => 'myorder不是字母',
'myorder.alphaNum' => 'myorder不是字母和数字',
'myorder.alphaDash' => 'myorder不是字母和数字和下划线及破折号',
'myorder.chs' => 'myorder只能是汉字',
'myorder.chsAlpha' => 'myorder只能是汉字、字母',
'myorder.chsAlphaNum' => 'myorder只能是汉字、字母和数字',
'myorder.chsDash' => 'myorder只能是汉字、字母、数字和下划线_及破折号-',
'myorder.activeUrl' => 'myorder不是有效的域名或者IP',
'myorder.url' => 'myorder不是有效的URL地址',
'myorder.ip' => 'myorder不是有效的IP地址',
'myorder.length' => 'myorder长度不符',
'myorder.max' => 'myorder超出最大长度',
'myorder.min' => 'myorder低于最小长度',
'classtype.require' => 'classtype不能为空',
'classtype.number' => 'classtype不是数字',
'classtype.float' => 'classtype不是小数',
'classtype.boolean' => 'classtype不是布尔值',
'classtype.email' => 'classtype不是邮箱地址',
'classtype.array' => 'classtype不是数组',
'classtype.accepted' => 'classtype请确认',
'classtype.date' => 'classtype不是有效日期',
'classtype.alpha' => 'classtype不是字母',
'classtype.alphaNum' => 'classtype不是字母和数字',
'classtype.alphaDash' => 'classtype不是字母和数字和下划线及破折号',
'classtype.chs' => 'classtype只能是汉字',
'classtype.chsAlpha' => 'classtype只能是汉字、字母',
'classtype.chsAlphaNum' => 'classtype只能是汉字、字母和数字',
'classtype.chsDash' => 'classtype只能是汉字、字母、数字和下划线_及破折号-',
'classtype.activeUrl' => 'classtype不是有效的域名或者IP',
'classtype.url' => 'classtype不是有效的URL地址',
'classtype.ip' => 'classtype不是有效的IP地址',
'classtype.length' => 'classtype长度不符',
'classtype.max' => 'classtype超出最大长度',
'classtype.min' => 'classtype低于最小长度',
'groupids.require' => 'groupids不能为空',
'groupids.number' => 'groupids不是数字',
'groupids.float' => 'groupids不是小数',
'groupids.boolean' => 'groupids不是布尔值',
'groupids.email' => 'groupids不是邮箱地址',
'groupids.array' => 'groupids不是数组',
'groupids.accepted' => 'groupids请确认',
'groupids.date' => 'groupids不是有效日期',
'groupids.alpha' => 'groupids不是字母',
'groupids.alphaNum' => 'groupids不是字母和数字',
'groupids.alphaDash' => 'groupids不是字母和数字和下划线及破折号',
'groupids.chs' => 'groupids只能是汉字',
'groupids.chsAlpha' => 'groupids只能是汉字、字母',
'groupids.chsAlphaNum' => 'groupids只能是汉字、字母和数字',
'groupids.chsDash' => 'groupids只能是汉字、字母、数字和下划线_及破折号-',
'groupids.activeUrl' => 'groupids不是有效的域名或者IP',
'groupids.url' => 'groupids不是有效的URL地址',
'groupids.ip' => 'groupids不是有效的IP地址',
'groupids.length' => 'groupids长度不符',
'groupids.max' => 'groupids超出最大长度',
'groupids.min' => 'groupids低于最小长度',
];

protected $scene =   [
    'add'=>['classid','classname','issys','myorder','classtype','groupids',],
    'edit'=>['classid','classname','issys','myorder','classtype','groupids',],
    'ck_id'=>['id']
];

}
