<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewsag extends Validate{

protected $rule =   [
        'agid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'agname' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'isadmin' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'auids' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'agid.require' => 'agid不能为空',
'agid.number' => 'agid不是数字',
'agid.float' => 'agid不是小数',
'agid.boolean' => 'agid不是布尔值',
'agid.email' => 'agid不是邮箱地址',
'agid.array' => 'agid不是数组',
'agid.accepted' => 'agid请确认',
'agid.date' => 'agid不是有效日期',
'agid.alpha' => 'agid不是字母',
'agid.alphaNum' => 'agid不是字母和数字',
'agid.alphaDash' => 'agid不是字母和数字和下划线及破折号',
'agid.chs' => 'agid只能是汉字',
'agid.chsAlpha' => 'agid只能是汉字、字母',
'agid.chsAlphaNum' => 'agid只能是汉字、字母和数字',
'agid.chsDash' => 'agid只能是汉字、字母、数字和下划线_及破折号-',
'agid.activeUrl' => 'agid不是有效的域名或者IP',
'agid.url' => 'agid不是有效的URL地址',
'agid.ip' => 'agid不是有效的IP地址',
'agid.length' => 'agid长度不符',
'agid.max' => 'agid超出最大长度',
'agid.min' => 'agid低于最小长度',
'agname.require' => 'agname不能为空',
'agname.number' => 'agname不是数字',
'agname.float' => 'agname不是小数',
'agname.boolean' => 'agname不是布尔值',
'agname.email' => 'agname不是邮箱地址',
'agname.array' => 'agname不是数组',
'agname.accepted' => 'agname请确认',
'agname.date' => 'agname不是有效日期',
'agname.alpha' => 'agname不是字母',
'agname.alphaNum' => 'agname不是字母和数字',
'agname.alphaDash' => 'agname不是字母和数字和下划线及破折号',
'agname.chs' => 'agname只能是汉字',
'agname.chsAlpha' => 'agname只能是汉字、字母',
'agname.chsAlphaNum' => 'agname只能是汉字、字母和数字',
'agname.chsDash' => 'agname只能是汉字、字母、数字和下划线_及破折号-',
'agname.activeUrl' => 'agname不是有效的域名或者IP',
'agname.url' => 'agname不是有效的URL地址',
'agname.ip' => 'agname不是有效的IP地址',
'agname.length' => 'agname长度不符',
'agname.max' => 'agname超出最大长度',
'agname.min' => 'agname低于最小长度',
'isadmin.require' => 'isadmin不能为空',
'isadmin.number' => 'isadmin不是数字',
'isadmin.float' => 'isadmin不是小数',
'isadmin.boolean' => 'isadmin不是布尔值',
'isadmin.email' => 'isadmin不是邮箱地址',
'isadmin.array' => 'isadmin不是数组',
'isadmin.accepted' => 'isadmin请确认',
'isadmin.date' => 'isadmin不是有效日期',
'isadmin.alpha' => 'isadmin不是字母',
'isadmin.alphaNum' => 'isadmin不是字母和数字',
'isadmin.alphaDash' => 'isadmin不是字母和数字和下划线及破折号',
'isadmin.chs' => 'isadmin只能是汉字',
'isadmin.chsAlpha' => 'isadmin只能是汉字、字母',
'isadmin.chsAlphaNum' => 'isadmin只能是汉字、字母和数字',
'isadmin.chsDash' => 'isadmin只能是汉字、字母、数字和下划线_及破折号-',
'isadmin.activeUrl' => 'isadmin不是有效的域名或者IP',
'isadmin.url' => 'isadmin不是有效的URL地址',
'isadmin.ip' => 'isadmin不是有效的IP地址',
'isadmin.length' => 'isadmin长度不符',
'isadmin.max' => 'isadmin超出最大长度',
'isadmin.min' => 'isadmin低于最小长度',
'auids.require' => 'auids不能为空',
'auids.number' => 'auids不是数字',
'auids.float' => 'auids不是小数',
'auids.boolean' => 'auids不是布尔值',
'auids.email' => 'auids不是邮箱地址',
'auids.array' => 'auids不是数组',
'auids.accepted' => 'auids请确认',
'auids.date' => 'auids不是有效日期',
'auids.alpha' => 'auids不是字母',
'auids.alphaNum' => 'auids不是字母和数字',
'auids.alphaDash' => 'auids不是字母和数字和下划线及破折号',
'auids.chs' => 'auids只能是汉字',
'auids.chsAlpha' => 'auids只能是汉字、字母',
'auids.chsAlphaNum' => 'auids只能是汉字、字母和数字',
'auids.chsDash' => 'auids只能是汉字、字母、数字和下划线_及破折号-',
'auids.activeUrl' => 'auids不是有效的域名或者IP',
'auids.url' => 'auids不是有效的URL地址',
'auids.ip' => 'auids不是有效的IP地址',
'auids.length' => 'auids长度不符',
'auids.max' => 'auids超出最大长度',
'auids.min' => 'auids低于最小长度',
];

protected $scene =   [
    'add'=>['agid','agname','isadmin','auids',],
    'edit'=>['agid','agname','isadmin','auids',],
    'ck_id'=>['id']
];

}
