<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class EnewsclassStatsSet extends Validate{

protected $rule =   [
        'openstats' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'pvtime' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'statsdate' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'changedate' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'openstats.require' => 'openstats不能为空',
'openstats.number' => 'openstats不是数字',
'openstats.float' => 'openstats不是小数',
'openstats.boolean' => 'openstats不是布尔值',
'openstats.email' => 'openstats不是邮箱地址',
'openstats.array' => 'openstats不是数组',
'openstats.accepted' => 'openstats请确认',
'openstats.date' => 'openstats不是有效日期',
'openstats.alpha' => 'openstats不是字母',
'openstats.alphaNum' => 'openstats不是字母和数字',
'openstats.alphaDash' => 'openstats不是字母和数字和下划线及破折号',
'openstats.chs' => 'openstats只能是汉字',
'openstats.chsAlpha' => 'openstats只能是汉字、字母',
'openstats.chsAlphaNum' => 'openstats只能是汉字、字母和数字',
'openstats.chsDash' => 'openstats只能是汉字、字母、数字和下划线_及破折号-',
'openstats.activeUrl' => 'openstats不是有效的域名或者IP',
'openstats.url' => 'openstats不是有效的URL地址',
'openstats.ip' => 'openstats不是有效的IP地址',
'openstats.length' => 'openstats长度不符',
'openstats.max' => 'openstats超出最大长度',
'openstats.min' => 'openstats低于最小长度',
'pvtime.require' => 'pvtime不能为空',
'pvtime.number' => 'pvtime不是数字',
'pvtime.float' => 'pvtime不是小数',
'pvtime.boolean' => 'pvtime不是布尔值',
'pvtime.email' => 'pvtime不是邮箱地址',
'pvtime.array' => 'pvtime不是数组',
'pvtime.accepted' => 'pvtime请确认',
'pvtime.date' => 'pvtime不是有效日期',
'pvtime.alpha' => 'pvtime不是字母',
'pvtime.alphaNum' => 'pvtime不是字母和数字',
'pvtime.alphaDash' => 'pvtime不是字母和数字和下划线及破折号',
'pvtime.chs' => 'pvtime只能是汉字',
'pvtime.chsAlpha' => 'pvtime只能是汉字、字母',
'pvtime.chsAlphaNum' => 'pvtime只能是汉字、字母和数字',
'pvtime.chsDash' => 'pvtime只能是汉字、字母、数字和下划线_及破折号-',
'pvtime.activeUrl' => 'pvtime不是有效的域名或者IP',
'pvtime.url' => 'pvtime不是有效的URL地址',
'pvtime.ip' => 'pvtime不是有效的IP地址',
'pvtime.length' => 'pvtime长度不符',
'pvtime.max' => 'pvtime超出最大长度',
'pvtime.min' => 'pvtime低于最小长度',
'statsdate.require' => 'statsdate不能为空',
'statsdate.number' => 'statsdate不是数字',
'statsdate.float' => 'statsdate不是小数',
'statsdate.boolean' => 'statsdate不是布尔值',
'statsdate.email' => 'statsdate不是邮箱地址',
'statsdate.array' => 'statsdate不是数组',
'statsdate.accepted' => 'statsdate请确认',
'statsdate.date' => 'statsdate不是有效日期',
'statsdate.alpha' => 'statsdate不是字母',
'statsdate.alphaNum' => 'statsdate不是字母和数字',
'statsdate.alphaDash' => 'statsdate不是字母和数字和下划线及破折号',
'statsdate.chs' => 'statsdate只能是汉字',
'statsdate.chsAlpha' => 'statsdate只能是汉字、字母',
'statsdate.chsAlphaNum' => 'statsdate只能是汉字、字母和数字',
'statsdate.chsDash' => 'statsdate只能是汉字、字母、数字和下划线_及破折号-',
'statsdate.activeUrl' => 'statsdate不是有效的域名或者IP',
'statsdate.url' => 'statsdate不是有效的URL地址',
'statsdate.ip' => 'statsdate不是有效的IP地址',
'statsdate.length' => 'statsdate长度不符',
'statsdate.max' => 'statsdate超出最大长度',
'statsdate.min' => 'statsdate低于最小长度',
'changedate.require' => 'changedate不能为空',
'changedate.number' => 'changedate不是数字',
'changedate.float' => 'changedate不是小数',
'changedate.boolean' => 'changedate不是布尔值',
'changedate.email' => 'changedate不是邮箱地址',
'changedate.array' => 'changedate不是数组',
'changedate.accepted' => 'changedate请确认',
'changedate.date' => 'changedate不是有效日期',
'changedate.alpha' => 'changedate不是字母',
'changedate.alphaNum' => 'changedate不是字母和数字',
'changedate.alphaDash' => 'changedate不是字母和数字和下划线及破折号',
'changedate.chs' => 'changedate只能是汉字',
'changedate.chsAlpha' => 'changedate只能是汉字、字母',
'changedate.chsAlphaNum' => 'changedate只能是汉字、字母和数字',
'changedate.chsDash' => 'changedate只能是汉字、字母、数字和下划线_及破折号-',
'changedate.activeUrl' => 'changedate不是有效的域名或者IP',
'changedate.url' => 'changedate不是有效的URL地址',
'changedate.ip' => 'changedate不是有效的IP地址',
'changedate.length' => 'changedate长度不符',
'changedate.max' => 'changedate超出最大长度',
'changedate.min' => 'changedate低于最小长度',
];

protected $scene =   [
    'add'=>['openstats','pvtime','statsdate','changedate',],
    'edit'=>['openstats','pvtime','statsdate','changedate',],
    'ck_id'=>['id']
];

}
