<?php
//由代码生成器自动生成
namespace app\index\validate;

use think\Validate;

class Enewstagsdata extends Validate{

protected $rule =   [
        'tid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'tagid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'classid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'id' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'newstime' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
        'mid' => 'require|number|float|boolean|email|array|accepted|date|alpha|alphaNum|alphaDash|chs|chsAlpha|chsAlphaNum|chsDash|activeUrl|url|ip|length:4,25|max:25|min:5',
    ];

protected $msg =   [
'tid.require' => 'tid不能为空',
'tid.number' => 'tid不是数字',
'tid.float' => 'tid不是小数',
'tid.boolean' => 'tid不是布尔值',
'tid.email' => 'tid不是邮箱地址',
'tid.array' => 'tid不是数组',
'tid.accepted' => 'tid请确认',
'tid.date' => 'tid不是有效日期',
'tid.alpha' => 'tid不是字母',
'tid.alphaNum' => 'tid不是字母和数字',
'tid.alphaDash' => 'tid不是字母和数字和下划线及破折号',
'tid.chs' => 'tid只能是汉字',
'tid.chsAlpha' => 'tid只能是汉字、字母',
'tid.chsAlphaNum' => 'tid只能是汉字、字母和数字',
'tid.chsDash' => 'tid只能是汉字、字母、数字和下划线_及破折号-',
'tid.activeUrl' => 'tid不是有效的域名或者IP',
'tid.url' => 'tid不是有效的URL地址',
'tid.ip' => 'tid不是有效的IP地址',
'tid.length' => 'tid长度不符',
'tid.max' => 'tid超出最大长度',
'tid.min' => 'tid低于最小长度',
'tagid.require' => 'tagid不能为空',
'tagid.number' => 'tagid不是数字',
'tagid.float' => 'tagid不是小数',
'tagid.boolean' => 'tagid不是布尔值',
'tagid.email' => 'tagid不是邮箱地址',
'tagid.array' => 'tagid不是数组',
'tagid.accepted' => 'tagid请确认',
'tagid.date' => 'tagid不是有效日期',
'tagid.alpha' => 'tagid不是字母',
'tagid.alphaNum' => 'tagid不是字母和数字',
'tagid.alphaDash' => 'tagid不是字母和数字和下划线及破折号',
'tagid.chs' => 'tagid只能是汉字',
'tagid.chsAlpha' => 'tagid只能是汉字、字母',
'tagid.chsAlphaNum' => 'tagid只能是汉字、字母和数字',
'tagid.chsDash' => 'tagid只能是汉字、字母、数字和下划线_及破折号-',
'tagid.activeUrl' => 'tagid不是有效的域名或者IP',
'tagid.url' => 'tagid不是有效的URL地址',
'tagid.ip' => 'tagid不是有效的IP地址',
'tagid.length' => 'tagid长度不符',
'tagid.max' => 'tagid超出最大长度',
'tagid.min' => 'tagid低于最小长度',
'classid.require' => 'classid不能为空',
'classid.number' => 'classid不是数字',
'classid.float' => 'classid不是小数',
'classid.boolean' => 'classid不是布尔值',
'classid.email' => 'classid不是邮箱地址',
'classid.array' => 'classid不是数组',
'classid.accepted' => 'classid请确认',
'classid.date' => 'classid不是有效日期',
'classid.alpha' => 'classid不是字母',
'classid.alphaNum' => 'classid不是字母和数字',
'classid.alphaDash' => 'classid不是字母和数字和下划线及破折号',
'classid.chs' => 'classid只能是汉字',
'classid.chsAlpha' => 'classid只能是汉字、字母',
'classid.chsAlphaNum' => 'classid只能是汉字、字母和数字',
'classid.chsDash' => 'classid只能是汉字、字母、数字和下划线_及破折号-',
'classid.activeUrl' => 'classid不是有效的域名或者IP',
'classid.url' => 'classid不是有效的URL地址',
'classid.ip' => 'classid不是有效的IP地址',
'classid.length' => 'classid长度不符',
'classid.max' => 'classid超出最大长度',
'classid.min' => 'classid低于最小长度',
'id.require' => 'id不能为空',
'id.number' => 'id不是数字',
'id.float' => 'id不是小数',
'id.boolean' => 'id不是布尔值',
'id.email' => 'id不是邮箱地址',
'id.array' => 'id不是数组',
'id.accepted' => 'id请确认',
'id.date' => 'id不是有效日期',
'id.alpha' => 'id不是字母',
'id.alphaNum' => 'id不是字母和数字',
'id.alphaDash' => 'id不是字母和数字和下划线及破折号',
'id.chs' => 'id只能是汉字',
'id.chsAlpha' => 'id只能是汉字、字母',
'id.chsAlphaNum' => 'id只能是汉字、字母和数字',
'id.chsDash' => 'id只能是汉字、字母、数字和下划线_及破折号-',
'id.activeUrl' => 'id不是有效的域名或者IP',
'id.url' => 'id不是有效的URL地址',
'id.ip' => 'id不是有效的IP地址',
'id.length' => 'id长度不符',
'id.max' => 'id超出最大长度',
'id.min' => 'id低于最小长度',
'newstime.require' => 'newstime不能为空',
'newstime.number' => 'newstime不是数字',
'newstime.float' => 'newstime不是小数',
'newstime.boolean' => 'newstime不是布尔值',
'newstime.email' => 'newstime不是邮箱地址',
'newstime.array' => 'newstime不是数组',
'newstime.accepted' => 'newstime请确认',
'newstime.date' => 'newstime不是有效日期',
'newstime.alpha' => 'newstime不是字母',
'newstime.alphaNum' => 'newstime不是字母和数字',
'newstime.alphaDash' => 'newstime不是字母和数字和下划线及破折号',
'newstime.chs' => 'newstime只能是汉字',
'newstime.chsAlpha' => 'newstime只能是汉字、字母',
'newstime.chsAlphaNum' => 'newstime只能是汉字、字母和数字',
'newstime.chsDash' => 'newstime只能是汉字、字母、数字和下划线_及破折号-',
'newstime.activeUrl' => 'newstime不是有效的域名或者IP',
'newstime.url' => 'newstime不是有效的URL地址',
'newstime.ip' => 'newstime不是有效的IP地址',
'newstime.length' => 'newstime长度不符',
'newstime.max' => 'newstime超出最大长度',
'newstime.min' => 'newstime低于最小长度',
'mid.require' => 'mid不能为空',
'mid.number' => 'mid不是数字',
'mid.float' => 'mid不是小数',
'mid.boolean' => 'mid不是布尔值',
'mid.email' => 'mid不是邮箱地址',
'mid.array' => 'mid不是数组',
'mid.accepted' => 'mid请确认',
'mid.date' => 'mid不是有效日期',
'mid.alpha' => 'mid不是字母',
'mid.alphaNum' => 'mid不是字母和数字',
'mid.alphaDash' => 'mid不是字母和数字和下划线及破折号',
'mid.chs' => 'mid只能是汉字',
'mid.chsAlpha' => 'mid只能是汉字、字母',
'mid.chsAlphaNum' => 'mid只能是汉字、字母和数字',
'mid.chsDash' => 'mid只能是汉字、字母、数字和下划线_及破折号-',
'mid.activeUrl' => 'mid不是有效的域名或者IP',
'mid.url' => 'mid不是有效的URL地址',
'mid.ip' => 'mid不是有效的IP地址',
'mid.length' => 'mid长度不符',
'mid.max' => 'mid超出最大长度',
'mid.min' => 'mid低于最小长度',
];

protected $scene =   [
    'add'=>['tid','tagid','classid','id','newstime','mid',],
    'edit'=>['tid','tagid','classid','id','newstime','mid',],
    'ck_id'=>['id']
];

}
